// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AppliedNodeStatusApplyConfiguration represents a declarative configuration of the AppliedNodeStatus type for use
// with apply.
//
// AppliedNodeStatus reports the per-BMC state resulting from HTP reconciliation.
type AppliedNodeStatusApplyConfiguration struct {
	// Name is the name of the BMC object.
	Name *string `json:"name,omitempty"`
	// Mode is the effective delivery mode for this BMC ("Polling" or "EventBased").
	Mode *string `json:"mode,omitempty"`
	// MRDActive is true when the controller has confirmed that the BMC-side
	// MetricReportDefinition is active and pushing data.
	MRDActive *bool `json:"mrdActive,omitempty"`
	// MRDSupported is false when the BMC rejected the MRD write or the
	// post-create probe found no data.
	MRDSupported *bool `json:"mrdSupported,omitempty"`
	// LastAppliedAt is the time the profile was last successfully applied to this BMC.
	LastAppliedAt *v1.Time `json:"lastAppliedAt,omitempty"`
}

// AppliedNodeStatusApplyConfiguration constructs a declarative configuration of the AppliedNodeStatus type for use with
// apply.
func AppliedNodeStatus() *AppliedNodeStatusApplyConfiguration {
	return &AppliedNodeStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AppliedNodeStatusApplyConfiguration) WithName(value string) *AppliedNodeStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *AppliedNodeStatusApplyConfiguration) WithMode(value string) *AppliedNodeStatusApplyConfiguration {
	b.Mode = &value
	return b
}

// WithMRDActive sets the MRDActive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MRDActive field is set to the value of the last call.
func (b *AppliedNodeStatusApplyConfiguration) WithMRDActive(value bool) *AppliedNodeStatusApplyConfiguration {
	b.MRDActive = &value
	return b
}

// WithMRDSupported sets the MRDSupported field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MRDSupported field is set to the value of the last call.
func (b *AppliedNodeStatusApplyConfiguration) WithMRDSupported(value bool) *AppliedNodeStatusApplyConfiguration {
	b.MRDSupported = &value
	return b
}

// WithLastAppliedAt sets the LastAppliedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastAppliedAt field is set to the value of the last call.
func (b *AppliedNodeStatusApplyConfiguration) WithLastAppliedAt(value v1.Time) *AppliedNodeStatusApplyConfiguration {
	b.LastAppliedAt = &value
	return b
}
