// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// BIOSSettingsTemplateApplyConfiguration represents a declarative configuration of the BIOSSettingsTemplate type for use
// with apply.
type BIOSSettingsTemplateApplyConfiguration struct {
	// Version specifies the software version (e.g. BIOS, BMC) these settings apply to.
	Version *string `json:"version,omitempty"`
	// SettingsFlow contains the BIOS settings sequence to apply in the given order.
	SettingsFlow []SettingsFlowItemApplyConfiguration `json:"settingsFlow,omitempty"`
	// ServerMaintenancePolicy is a maintenance policy to be enforced on the server.
	ServerMaintenancePolicy *apiv1alpha1.ServerMaintenancePolicy `json:"serverMaintenancePolicy,omitempty"`
}

// BIOSSettingsTemplateApplyConfiguration constructs a declarative configuration of the BIOSSettingsTemplate type for use with
// apply.
func BIOSSettingsTemplate() *BIOSSettingsTemplateApplyConfiguration {
	return &BIOSSettingsTemplateApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *BIOSSettingsTemplateApplyConfiguration) WithVersion(value string) *BIOSSettingsTemplateApplyConfiguration {
	b.Version = &value
	return b
}

// WithSettingsFlow adds the given value to the SettingsFlow field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SettingsFlow field.
func (b *BIOSSettingsTemplateApplyConfiguration) WithSettingsFlow(values ...*SettingsFlowItemApplyConfiguration) *BIOSSettingsTemplateApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSettingsFlow")
		}
		b.SettingsFlow = append(b.SettingsFlow, *values[i])
	}
	return b
}

// WithServerMaintenancePolicy sets the ServerMaintenancePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerMaintenancePolicy field is set to the value of the last call.
func (b *BIOSSettingsTemplateApplyConfiguration) WithServerMaintenancePolicy(value apiv1alpha1.ServerMaintenancePolicy) *BIOSSettingsTemplateApplyConfiguration {
	b.ServerMaintenancePolicy = &value
	return b
}
