// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BIOSVersionSetStatusApplyConfiguration represents a declarative configuration of the BIOSVersionSetStatus type for use
// with apply.
//
// BIOSVersionSetStatus defines the observed state of BIOSVersionSet.
type BIOSVersionSetStatusApplyConfiguration struct {
	// FullyLabeledServers is the number of servers in the set.
	FullyLabeledServers *int32 `json:"fullyLabeledServers,omitempty"`
	// AvailableBIOSVersion is the number of BIOSVersion created by the set.
	AvailableBIOSVersion *int32 `json:"availableBIOSVersion,omitempty"`
	// PendingBIOSVersion is the total number of pending BIOSVersion in the set.
	PendingBIOSVersion *int32 `json:"pendingBIOSVersion,omitempty"`
	// InProgressBIOSVersion is the total number of BIOSVersion resources in the set that are currently in progress.
	InProgressBIOSVersion *int32 `json:"inProgressBIOSVersion,omitempty"`
	// CompletedBIOSVersion is the total number of completed BIOSVersion in the set.
	CompletedBIOSVersion *int32 `json:"completedBIOSVersion,omitempty"`
	// FailedBIOSVersion is the total number of failed BIOSVersion in the set.
	FailedBIOSVersion *int32 `json:"failedBIOSVersion,omitempty"`
}

// BIOSVersionSetStatusApplyConfiguration constructs a declarative configuration of the BIOSVersionSetStatus type for use with
// apply.
func BIOSVersionSetStatus() *BIOSVersionSetStatusApplyConfiguration {
	return &BIOSVersionSetStatusApplyConfiguration{}
}

// WithFullyLabeledServers sets the FullyLabeledServers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullyLabeledServers field is set to the value of the last call.
func (b *BIOSVersionSetStatusApplyConfiguration) WithFullyLabeledServers(value int32) *BIOSVersionSetStatusApplyConfiguration {
	b.FullyLabeledServers = &value
	return b
}

// WithAvailableBIOSVersion sets the AvailableBIOSVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableBIOSVersion field is set to the value of the last call.
func (b *BIOSVersionSetStatusApplyConfiguration) WithAvailableBIOSVersion(value int32) *BIOSVersionSetStatusApplyConfiguration {
	b.AvailableBIOSVersion = &value
	return b
}

// WithPendingBIOSVersion sets the PendingBIOSVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PendingBIOSVersion field is set to the value of the last call.
func (b *BIOSVersionSetStatusApplyConfiguration) WithPendingBIOSVersion(value int32) *BIOSVersionSetStatusApplyConfiguration {
	b.PendingBIOSVersion = &value
	return b
}

// WithInProgressBIOSVersion sets the InProgressBIOSVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InProgressBIOSVersion field is set to the value of the last call.
func (b *BIOSVersionSetStatusApplyConfiguration) WithInProgressBIOSVersion(value int32) *BIOSVersionSetStatusApplyConfiguration {
	b.InProgressBIOSVersion = &value
	return b
}

// WithCompletedBIOSVersion sets the CompletedBIOSVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedBIOSVersion field is set to the value of the last call.
func (b *BIOSVersionSetStatusApplyConfiguration) WithCompletedBIOSVersion(value int32) *BIOSVersionSetStatusApplyConfiguration {
	b.CompletedBIOSVersion = &value
	return b
}

// WithFailedBIOSVersion sets the FailedBIOSVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedBIOSVersion field is set to the value of the last call.
func (b *BIOSVersionSetStatusApplyConfiguration) WithFailedBIOSVersion(value int32) *BIOSVersionSetStatusApplyConfiguration {
	b.FailedBIOSVersion = &value
	return b
}
