// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BIOSVersionStatusApplyConfiguration represents a declarative configuration of the BIOSVersionStatus type for use
// with apply.
//
// BIOSVersionStatus defines the observed state of BIOSVersion.
type BIOSVersionStatusApplyConfiguration struct {
	// State represents the current state of the BIOS upgrade task.
	State *apiv1alpha1.BIOSVersionState `json:"state,omitempty"`
	// UpgradeTask contains the state of the Upgrade Task created by the BMC
	UpgradeTask *TaskApplyConfiguration `json:"upgradeTask,omitempty"`
	// Conditions represents the latest available observations of the BIOS version upgrade state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// BIOSVersionStatusApplyConfiguration constructs a declarative configuration of the BIOSVersionStatus type for use with
// apply.
func BIOSVersionStatus() *BIOSVersionStatusApplyConfiguration {
	return &BIOSVersionStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *BIOSVersionStatusApplyConfiguration) WithState(value apiv1alpha1.BIOSVersionState) *BIOSVersionStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithUpgradeTask sets the UpgradeTask field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpgradeTask field is set to the value of the last call.
func (b *BIOSVersionStatusApplyConfiguration) WithUpgradeTask(value *TaskApplyConfiguration) *BIOSVersionStatusApplyConfiguration {
	b.UpgradeTask = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BIOSVersionStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BIOSVersionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
