// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BIOSSettingsFlowStatusApplyConfiguration represents a declarative configuration of the BIOSSettingsFlowStatus type for use
// with apply.
type BIOSSettingsFlowStatusApplyConfiguration struct {
	// State represents the current state of the BIOS settings update for the current priority.
	State *apiv1alpha1.BIOSSettingsFlowState `json:"flowState,omitempty"`
	// Name identifies the current priority settings from the spec.
	Name *string `json:"name,omitempty"`
	// Priority identifies the settings priority from the spec.
	Priority *int32 `json:"priority,omitempty"`
	// Conditions represents the latest available observations of the BIOSSettings's current Flowstate.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// LastAppliedTime represents the timestamp when the last setting was successfully applied.
	LastAppliedTime *metav1.Time `json:"lastAppliedTime,omitempty"`
}

// BIOSSettingsFlowStatusApplyConfiguration constructs a declarative configuration of the BIOSSettingsFlowStatus type for use with
// apply.
func BIOSSettingsFlowStatus() *BIOSSettingsFlowStatusApplyConfiguration {
	return &BIOSSettingsFlowStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *BIOSSettingsFlowStatusApplyConfiguration) WithState(value apiv1alpha1.BIOSSettingsFlowState) *BIOSSettingsFlowStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BIOSSettingsFlowStatusApplyConfiguration) WithName(value string) *BIOSSettingsFlowStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *BIOSSettingsFlowStatusApplyConfiguration) WithPriority(value int32) *BIOSSettingsFlowStatusApplyConfiguration {
	b.Priority = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BIOSSettingsFlowStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BIOSSettingsFlowStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithLastAppliedTime sets the LastAppliedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastAppliedTime field is set to the value of the last call.
func (b *BIOSSettingsFlowStatusApplyConfiguration) WithLastAppliedTime(value metav1.Time) *BIOSSettingsFlowStatusApplyConfiguration {
	b.LastAppliedTime = &value
	return b
}
