// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	internal "github.com/ironcore-dev/metal-operator/api/v1alpha1/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BIOSSettingsSetApplyConfiguration represents a declarative configuration of the BIOSSettingsSet type for use
// with apply.
//
// BIOSSettingsSet is the Schema for the biossettingssets API.
//
// Deprecated: The BIOSSettingsSet resource is deprecated.
type BIOSSettingsSetApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *BIOSSettingsSetSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *BIOSSettingsSetStatusApplyConfiguration `json:"status,omitempty"`
}

// BIOSSettingsSet constructs a declarative configuration of the BIOSSettingsSet type for use with
// apply.
func BIOSSettingsSet(name string) *BIOSSettingsSetApplyConfiguration {
	b := &BIOSSettingsSetApplyConfiguration{}
	b.WithName(name)
	b.WithKind("BIOSSettingsSet")
	b.WithAPIVersion("metal.ironcore.dev/v1alpha1")
	return b
}

// ExtractBIOSSettingsSetFrom extracts the applied configuration owned by fieldManager from
// bIOSSettingsSet for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// bIOSSettingsSet must be a unmodified BIOSSettingsSet API object that was retrieved from the Kubernetes API.
// ExtractBIOSSettingsSetFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractBIOSSettingsSetFrom(bIOSSettingsSet *apiv1alpha1.BIOSSettingsSet, fieldManager string, subresource string) (*BIOSSettingsSetApplyConfiguration, error) {
	b := &BIOSSettingsSetApplyConfiguration{}
	err := managedfields.ExtractInto(bIOSSettingsSet, internal.Parser().Type("com.github.ironcore-dev.metal-operator.api.v1alpha1.BIOSSettingsSet"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(bIOSSettingsSet.Name)

	b.WithKind("BIOSSettingsSet")
	b.WithAPIVersion("metal.ironcore.dev/v1alpha1")
	return b, nil
}

// ExtractBIOSSettingsSet extracts the applied configuration owned by fieldManager from
// bIOSSettingsSet. If no managedFields are found in bIOSSettingsSet for fieldManager, a
// BIOSSettingsSetApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// bIOSSettingsSet must be a unmodified BIOSSettingsSet API object that was retrieved from the Kubernetes API.
// ExtractBIOSSettingsSet provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractBIOSSettingsSet(bIOSSettingsSet *apiv1alpha1.BIOSSettingsSet, fieldManager string) (*BIOSSettingsSetApplyConfiguration, error) {
	return ExtractBIOSSettingsSetFrom(bIOSSettingsSet, fieldManager, "")
}

// ExtractBIOSSettingsSetStatus extracts the applied configuration owned by fieldManager from
// bIOSSettingsSet for the status subresource.
func ExtractBIOSSettingsSetStatus(bIOSSettingsSet *apiv1alpha1.BIOSSettingsSet, fieldManager string) (*BIOSSettingsSetApplyConfiguration, error) {
	return ExtractBIOSSettingsSetFrom(bIOSSettingsSet, fieldManager, "status")
}

func (b BIOSSettingsSetApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithKind(value string) *BIOSSettingsSetApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithAPIVersion(value string) *BIOSSettingsSetApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithName(value string) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithGenerateName(value string) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithNamespace(value string) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithUID(value types.UID) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithResourceVersion(value string) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithGeneration(value int64) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithCreationTimestamp(value metav1.Time) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *BIOSSettingsSetApplyConfiguration) WithLabels(entries map[string]string) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *BIOSSettingsSetApplyConfiguration) WithAnnotations(entries map[string]string) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *BIOSSettingsSetApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *BIOSSettingsSetApplyConfiguration) WithFinalizers(values ...string) *BIOSSettingsSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *BIOSSettingsSetApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithSpec(value *BIOSSettingsSetSpecApplyConfiguration) *BIOSSettingsSetApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *BIOSSettingsSetApplyConfiguration) WithStatus(value *BIOSSettingsSetStatusApplyConfiguration) *BIOSSettingsSetApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *BIOSSettingsSetApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *BIOSSettingsSetApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *BIOSSettingsSetApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *BIOSSettingsSetApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
