// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// BIOSSettingsSpecApplyConfiguration represents a declarative configuration of the BIOSSettingsSpec type for use
// with apply.
//
// BIOSSettingsSpec defines the desired state of BIOSSettings.
type BIOSSettingsSpecApplyConfiguration struct {
	// BIOSSettingsTemplate defines the template for BIOS Settings to be applied on the servers.
	BIOSSettingsTemplateApplyConfiguration `json:",inline"`
	// ServerMaintenanceRef is a reference to a ServerMaintenance object that BIOSSettings has requested for the referred server.
	ServerMaintenanceRef *ObjectReferenceApplyConfiguration `json:"serverMaintenanceRef,omitempty"`
	// ServerRef is a reference to a specific server to apply the BIOS settings on.
	ServerRef *v1.LocalObjectReference `json:"serverRef,omitempty"`
}

// BIOSSettingsSpecApplyConfiguration constructs a declarative configuration of the BIOSSettingsSpec type for use with
// apply.
func BIOSSettingsSpec() *BIOSSettingsSpecApplyConfiguration {
	return &BIOSSettingsSpecApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *BIOSSettingsSpecApplyConfiguration) WithVersion(value string) *BIOSSettingsSpecApplyConfiguration {
	b.BIOSSettingsTemplateApplyConfiguration.Version = &value
	return b
}

// WithSettingsFlow adds the given value to the SettingsFlow field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SettingsFlow field.
func (b *BIOSSettingsSpecApplyConfiguration) WithSettingsFlow(values ...*SettingsFlowItemApplyConfiguration) *BIOSSettingsSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSettingsFlow")
		}
		b.BIOSSettingsTemplateApplyConfiguration.SettingsFlow = append(b.BIOSSettingsTemplateApplyConfiguration.SettingsFlow, *values[i])
	}
	return b
}

// WithServerMaintenancePolicy sets the ServerMaintenancePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerMaintenancePolicy field is set to the value of the last call.
func (b *BIOSSettingsSpecApplyConfiguration) WithServerMaintenancePolicy(value apiv1alpha1.ServerMaintenancePolicy) *BIOSSettingsSpecApplyConfiguration {
	b.BIOSSettingsTemplateApplyConfiguration.ServerMaintenancePolicy = &value
	return b
}

// WithServerMaintenanceRef sets the ServerMaintenanceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerMaintenanceRef field is set to the value of the last call.
func (b *BIOSSettingsSpecApplyConfiguration) WithServerMaintenanceRef(value *ObjectReferenceApplyConfiguration) *BIOSSettingsSpecApplyConfiguration {
	b.ServerMaintenanceRef = value
	return b
}

// WithServerRef sets the ServerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerRef field is set to the value of the last call.
func (b *BIOSSettingsSpecApplyConfiguration) WithServerRef(value v1.LocalObjectReference) *BIOSSettingsSpecApplyConfiguration {
	b.ServerRef = &value
	return b
}
