// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BIOSSettingsSetStatusApplyConfiguration represents a declarative configuration of the BIOSSettingsSetStatus type for use
// with apply.
//
// BIOSSettingsSetStatus defines the observed state of BIOSSettingsSet.
type BIOSSettingsSetStatusApplyConfiguration struct {
	// FullyLabeledServers is the number of servers in the set.
	FullyLabeledServers *int32 `json:"fullyLabeledServers,omitempty"`
	// AvailableBIOSSettings is the number of BIOSSettings currently created by the set.
	AvailableBIOSSettings *int32 `json:"availableBIOSSettings,omitempty"`
	// PendingBIOSSettings is the total number of pending BIOSSettings in the set.
	PendingBIOSSettings *int32 `json:"pendingBIOSSettings,omitempty"`
	// InProgressBIOSSettings is the total number of BIOSSettings in the set that are currently in progress.
	InProgressBIOSSettings *int32 `json:"inProgressBIOSSettings,omitempty"`
	// CompletedBIOSSettings is the total number of completed BIOSSettings in the set.
	CompletedBIOSSettings *int32 `json:"completedBIOSSettings,omitempty"`
	// FailedBIOSSettings is the total number of failed BIOSSettings in the set.
	FailedBIOSSettings *int32 `json:"failedBIOSSettings,omitempty"`
}

// BIOSSettingsSetStatusApplyConfiguration constructs a declarative configuration of the BIOSSettingsSetStatus type for use with
// apply.
func BIOSSettingsSetStatus() *BIOSSettingsSetStatusApplyConfiguration {
	return &BIOSSettingsSetStatusApplyConfiguration{}
}

// WithFullyLabeledServers sets the FullyLabeledServers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullyLabeledServers field is set to the value of the last call.
func (b *BIOSSettingsSetStatusApplyConfiguration) WithFullyLabeledServers(value int32) *BIOSSettingsSetStatusApplyConfiguration {
	b.FullyLabeledServers = &value
	return b
}

// WithAvailableBIOSSettings sets the AvailableBIOSSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableBIOSSettings field is set to the value of the last call.
func (b *BIOSSettingsSetStatusApplyConfiguration) WithAvailableBIOSSettings(value int32) *BIOSSettingsSetStatusApplyConfiguration {
	b.AvailableBIOSSettings = &value
	return b
}

// WithPendingBIOSSettings sets the PendingBIOSSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PendingBIOSSettings field is set to the value of the last call.
func (b *BIOSSettingsSetStatusApplyConfiguration) WithPendingBIOSSettings(value int32) *BIOSSettingsSetStatusApplyConfiguration {
	b.PendingBIOSSettings = &value
	return b
}

// WithInProgressBIOSSettings sets the InProgressBIOSSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InProgressBIOSSettings field is set to the value of the last call.
func (b *BIOSSettingsSetStatusApplyConfiguration) WithInProgressBIOSSettings(value int32) *BIOSSettingsSetStatusApplyConfiguration {
	b.InProgressBIOSSettings = &value
	return b
}

// WithCompletedBIOSSettings sets the CompletedBIOSSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedBIOSSettings field is set to the value of the last call.
func (b *BIOSSettingsSetStatusApplyConfiguration) WithCompletedBIOSSettings(value int32) *BIOSSettingsSetStatusApplyConfiguration {
	b.CompletedBIOSSettings = &value
	return b
}

// WithFailedBIOSSettings sets the FailedBIOSSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedBIOSSettings field is set to the value of the last call.
func (b *BIOSSettingsSetStatusApplyConfiguration) WithFailedBIOSSettings(value int32) *BIOSSettingsSetStatusApplyConfiguration {
	b.FailedBIOSSettings = &value
	return b
}
