// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BIOSSettingsStatusApplyConfiguration represents a declarative configuration of the BIOSSettingsStatus type for use
// with apply.
//
// BIOSSettingsStatus defines the observed state of BIOSSettings.
type BIOSSettingsStatusApplyConfiguration struct {
	// State represents the current state of the BIOS settings update.
	State *apiv1alpha1.BIOSSettingsState `json:"state,omitempty"`
	// FlowState is a list of individual BIOSSettings operation flows.
	FlowState []BIOSSettingsFlowStatusApplyConfiguration `json:"flowState,omitempty"`
	// LastAppliedTime represents the timestamp when the last setting was successfully applied.
	LastAppliedTime *v1.Time `json:"lastAppliedTime,omitempty"`
	// FailedAttempts is the number of automatic retry attempts made after failure.
	FailedAttempts *int32 `json:"failedAttempts,omitempty"`
	// ObservedGeneration is the most recent generation observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represents the latest available observations of the BIOSSettings's current state.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// BIOSSettingsStatusApplyConfiguration constructs a declarative configuration of the BIOSSettingsStatus type for use with
// apply.
func BIOSSettingsStatus() *BIOSSettingsStatusApplyConfiguration {
	return &BIOSSettingsStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *BIOSSettingsStatusApplyConfiguration) WithState(value apiv1alpha1.BIOSSettingsState) *BIOSSettingsStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithFlowState adds the given value to the FlowState field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FlowState field.
func (b *BIOSSettingsStatusApplyConfiguration) WithFlowState(values ...*BIOSSettingsFlowStatusApplyConfiguration) *BIOSSettingsStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFlowState")
		}
		b.FlowState = append(b.FlowState, *values[i])
	}
	return b
}

// WithLastAppliedTime sets the LastAppliedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastAppliedTime field is set to the value of the last call.
func (b *BIOSSettingsStatusApplyConfiguration) WithLastAppliedTime(value v1.Time) *BIOSSettingsStatusApplyConfiguration {
	b.LastAppliedTime = &value
	return b
}

// WithFailedAttempts sets the FailedAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedAttempts field is set to the value of the last call.
func (b *BIOSSettingsStatusApplyConfiguration) WithFailedAttempts(value int32) *BIOSSettingsStatusApplyConfiguration {
	b.FailedAttempts = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BIOSSettingsStatusApplyConfiguration) WithObservedGeneration(value int64) *BIOSSettingsStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BIOSSettingsStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *BIOSSettingsStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
