// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BIOSSettingsSetSpecApplyConfiguration represents a declarative configuration of the BIOSSettingsSetSpec type for use
// with apply.
//
// BIOSSettingsSetSpec defines the desired state of BIOSSettingsSet.
type BIOSSettingsSetSpecApplyConfiguration struct {
	// BIOSSettingsTemplate defines the template for the BIOSSettings resource to be applied to the servers.
	BIOSSettingsTemplate *BIOSSettingsTemplateApplyConfiguration `json:"biosSettingsTemplate,omitempty"`
	// ServerSelector specifies a label selector to identify the servers that are to be selected.
	ServerSelector *v1.LabelSelectorApplyConfiguration `json:"serverSelector,omitempty"`
}

// BIOSSettingsSetSpecApplyConfiguration constructs a declarative configuration of the BIOSSettingsSetSpec type for use with
// apply.
func BIOSSettingsSetSpec() *BIOSSettingsSetSpecApplyConfiguration {
	return &BIOSSettingsSetSpecApplyConfiguration{}
}

// WithBIOSSettingsTemplate sets the BIOSSettingsTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BIOSSettingsTemplate field is set to the value of the last call.
func (b *BIOSSettingsSetSpecApplyConfiguration) WithBIOSSettingsTemplate(value *BIOSSettingsTemplateApplyConfiguration) *BIOSSettingsSetSpecApplyConfiguration {
	b.BIOSSettingsTemplate = value
	return b
}

// WithServerSelector sets the ServerSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerSelector field is set to the value of the last call.
func (b *BIOSSettingsSetSpecApplyConfiguration) WithServerSelector(value *v1.LabelSelectorApplyConfiguration) *BIOSSettingsSetSpecApplyConfiguration {
	b.ServerSelector = value
	return b
}
