// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// BMCAccessApplyConfiguration represents a declarative configuration of the BMCAccess type for use
// with apply.
//
// BMCAccess defines the access details for the BMC.
type BMCAccessApplyConfiguration struct {
	// Protocol specifies the protocol to be used for communicating with the BMC.
	Protocol *ProtocolApplyConfiguration `json:"protocol,omitempty"`
	// Address is the address of the BMC.
	Address *string `json:"address,omitempty"`
	// BMCSecretRef is a reference to the BMCSecret object that contains the credentials
	// required to access the BMC.
	BMCSecretRef *v1.LocalObjectReference `json:"bmcSecretRef,omitempty"`
}

// BMCAccessApplyConfiguration constructs a declarative configuration of the BMCAccess type for use with
// apply.
func BMCAccess() *BMCAccessApplyConfiguration {
	return &BMCAccessApplyConfiguration{}
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *BMCAccessApplyConfiguration) WithProtocol(value *ProtocolApplyConfiguration) *BMCAccessApplyConfiguration {
	b.Protocol = value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *BMCAccessApplyConfiguration) WithAddress(value string) *BMCAccessApplyConfiguration {
	b.Address = &value
	return b
}

// WithBMCSecretRef sets the BMCSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSecretRef field is set to the value of the last call.
func (b *BMCAccessApplyConfiguration) WithBMCSecretRef(value v1.LocalObjectReference) *BMCAccessApplyConfiguration {
	b.BMCSecretRef = &value
	return b
}
