// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BMCStatusApplyConfiguration represents a declarative configuration of the BMCStatus type for use
// with apply.
//
// BMCStatus defines the observed state of BMC.
type BMCStatusApplyConfiguration struct {
	// MACAddress is the MAC address of the BMC.
	MACAddress *string `json:"macAddress,omitempty"`
	// IP is the IP address of the BMC.
	IP *apiv1alpha1.IP `json:"ip,omitempty"`
	// Manufacturer is the name of the BMC manufacturer.
	Manufacturer *string `json:"manufacturer,omitempty"`
	// Model is the model number or name of the BMC.
	Model *string `json:"model,omitempty"`
	// SKU is the stock keeping unit identifier for the BMC.
	SKU *string `json:"sku,omitempty"`
	// SerialNumber is the serial number of the BMC.
	SerialNumber *string `json:"serialNumber,omitempty"`
	// FirmwareVersion is the version of the firmware currently running on the BMC.
	FirmwareVersion *string `json:"firmwareVersion,omitempty"`
	// State represents the current state of the BMC.
	// kubebuilder:validation:Enum=Enabled;Error;Pending
	State *apiv1alpha1.BMCState `json:"state,omitempty"`
	// PowerState represents the current power state of the BMC.
	PowerState *apiv1alpha1.BMCPowerState `json:"powerState,omitempty"`
	// LastResetTime is the timestamp of the last reset operation performed on the BMC.
	LastResetTime *v1.Time `json:"lastResetTime,omitempty"`
	// MetricsReportSubscriptionLink is the link to the metrics report subscription of the bmc.
	MetricsReportSubscriptionLink *string `json:"metricsReportSubscriptionLink,omitempty"`
	// EventsSubscriptionLink is the link to the events subscription of the bmc.
	EventsSubscriptionLink *string `json:"eventsSubscriptionLink,omitempty"`
	// Conditions represents the latest available observations of the BMC's current state.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// BMCStatusApplyConfiguration constructs a declarative configuration of the BMCStatus type for use with
// apply.
func BMCStatus() *BMCStatusApplyConfiguration {
	return &BMCStatusApplyConfiguration{}
}

// WithMACAddress sets the MACAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MACAddress field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithMACAddress(value string) *BMCStatusApplyConfiguration {
	b.MACAddress = &value
	return b
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithIP(value apiv1alpha1.IP) *BMCStatusApplyConfiguration {
	b.IP = &value
	return b
}

// WithManufacturer sets the Manufacturer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manufacturer field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithManufacturer(value string) *BMCStatusApplyConfiguration {
	b.Manufacturer = &value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithModel(value string) *BMCStatusApplyConfiguration {
	b.Model = &value
	return b
}

// WithSKU sets the SKU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SKU field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithSKU(value string) *BMCStatusApplyConfiguration {
	b.SKU = &value
	return b
}

// WithSerialNumber sets the SerialNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SerialNumber field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithSerialNumber(value string) *BMCStatusApplyConfiguration {
	b.SerialNumber = &value
	return b
}

// WithFirmwareVersion sets the FirmwareVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirmwareVersion field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithFirmwareVersion(value string) *BMCStatusApplyConfiguration {
	b.FirmwareVersion = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithState(value apiv1alpha1.BMCState) *BMCStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithPowerState sets the PowerState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PowerState field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithPowerState(value apiv1alpha1.BMCPowerState) *BMCStatusApplyConfiguration {
	b.PowerState = &value
	return b
}

// WithLastResetTime sets the LastResetTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastResetTime field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithLastResetTime(value v1.Time) *BMCStatusApplyConfiguration {
	b.LastResetTime = &value
	return b
}

// WithMetricsReportSubscriptionLink sets the MetricsReportSubscriptionLink field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricsReportSubscriptionLink field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithMetricsReportSubscriptionLink(value string) *BMCStatusApplyConfiguration {
	b.MetricsReportSubscriptionLink = &value
	return b
}

// WithEventsSubscriptionLink sets the EventsSubscriptionLink field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EventsSubscriptionLink field is set to the value of the last call.
func (b *BMCStatusApplyConfiguration) WithEventsSubscriptionLink(value string) *BMCStatusApplyConfiguration {
	b.EventsSubscriptionLink = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BMCStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *BMCStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
