// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BMCSettingsSetSpecApplyConfiguration represents a declarative configuration of the BMCSettingsSetSpec type for use
// with apply.
//
// BMCSettingsSetSpec defines the desired state of BMCSettingsSet.
type BMCSettingsSetSpecApplyConfiguration struct {
	// BMCSettingsTemplate defines the template for the BMCSettings resource to be applied to the BMCs.
	BMCSettingsTemplate *BMCSettingsTemplateApplyConfiguration `json:"bmcSettingsTemplate,omitempty"`
	// DynamicSettings defines dynamic settings to resolve per BMC when creating BMCSettings resources.
	DynamicSettings []DynamicSettingApplyConfiguration `json:"dynamicSettings,omitempty"`
	// BMCSelector specifies a label selector to identify the BMCs to be selected.
	BMCSelector *v1.LabelSelectorApplyConfiguration `json:"bmcSelector,omitempty"`
}

// BMCSettingsSetSpecApplyConfiguration constructs a declarative configuration of the BMCSettingsSetSpec type for use with
// apply.
func BMCSettingsSetSpec() *BMCSettingsSetSpecApplyConfiguration {
	return &BMCSettingsSetSpecApplyConfiguration{}
}

// WithBMCSettingsTemplate sets the BMCSettingsTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSettingsTemplate field is set to the value of the last call.
func (b *BMCSettingsSetSpecApplyConfiguration) WithBMCSettingsTemplate(value *BMCSettingsTemplateApplyConfiguration) *BMCSettingsSetSpecApplyConfiguration {
	b.BMCSettingsTemplate = value
	return b
}

// WithDynamicSettings adds the given value to the DynamicSettings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DynamicSettings field.
func (b *BMCSettingsSetSpecApplyConfiguration) WithDynamicSettings(values ...*DynamicSettingApplyConfiguration) *BMCSettingsSetSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDynamicSettings")
		}
		b.DynamicSettings = append(b.DynamicSettings, *values[i])
	}
	return b
}

// WithBMCSelector sets the BMCSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSelector field is set to the value of the last call.
func (b *BMCSettingsSetSpecApplyConfiguration) WithBMCSelector(value *v1.LabelSelectorApplyConfiguration) *BMCSettingsSetSpecApplyConfiguration {
	b.BMCSelector = value
	return b
}
