// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// BMCSpecApplyConfiguration represents a declarative configuration of the BMCSpec type for use
// with apply.
//
// BMCSpec defines the desired state of BMC
type BMCSpecApplyConfiguration struct {
	// BMCUUID is the unique identifier for the BMC as defined in Redfish API.
	BMCUUID *string `json:"bmcUUID,omitempty"`
	// EndpointRef is a reference to the Endpoint object that contains the network access information for the BMC.
	EndpointRef *v1.LocalObjectReference `json:"endpointRef,omitempty"`
	// Endpoint specifies inline network access details for the BMC.
	Endpoint *InlineEndpointApplyConfiguration `json:"access,omitempty"`
	// BMCSecretRef is a reference to the BMCSecret object that contains the credentials
	// required to access the BMC.
	BMCSecretRef *v1.LocalObjectReference `json:"bmcSecretRef,omitempty"`
	// Protocol specifies the protocol to be used for communicating with the BMC.
	Protocol *ProtocolApplyConfiguration `json:"protocol,omitempty"`
	// ConsoleProtocol specifies the protocol to be used for console access to the BMC.
	ConsoleProtocol *ConsoleProtocolApplyConfiguration `json:"consoleProtocol,omitempty"`
	// BMCSettingRef is a reference to a BMCSettings object that specifies
	// the BMC configuration for this BMC.
	// Deprecated: use bmcSettingsRefs instead. Will be removed in next release.
	BMCSettingRef *v1.LocalObjectReference `json:"bmcSettingsRef,omitempty"`
	// BMCSettingsRefs is a list of references to BMCSettings objects that specify
	// the BMC configuration for this BMC. Replaces the single bmcSettingsRef to support
	// multiple simultaneous settings objects created.
	BMCSettingsRefs []v1.LocalObjectReference `json:"bmcSettingsRefs,omitempty"`
	// Hostname is the hostname of the BMC.
	Hostname *string `json:"hostname,omitempty"`
}

// BMCSpecApplyConfiguration constructs a declarative configuration of the BMCSpec type for use with
// apply.
func BMCSpec() *BMCSpecApplyConfiguration {
	return &BMCSpecApplyConfiguration{}
}

// WithBMCUUID sets the BMCUUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCUUID field is set to the value of the last call.
func (b *BMCSpecApplyConfiguration) WithBMCUUID(value string) *BMCSpecApplyConfiguration {
	b.BMCUUID = &value
	return b
}

// WithEndpointRef sets the EndpointRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndpointRef field is set to the value of the last call.
func (b *BMCSpecApplyConfiguration) WithEndpointRef(value v1.LocalObjectReference) *BMCSpecApplyConfiguration {
	b.EndpointRef = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *BMCSpecApplyConfiguration) WithEndpoint(value *InlineEndpointApplyConfiguration) *BMCSpecApplyConfiguration {
	b.Endpoint = value
	return b
}

// WithBMCSecretRef sets the BMCSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSecretRef field is set to the value of the last call.
func (b *BMCSpecApplyConfiguration) WithBMCSecretRef(value v1.LocalObjectReference) *BMCSpecApplyConfiguration {
	b.BMCSecretRef = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *BMCSpecApplyConfiguration) WithProtocol(value *ProtocolApplyConfiguration) *BMCSpecApplyConfiguration {
	b.Protocol = value
	return b
}

// WithConsoleProtocol sets the ConsoleProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsoleProtocol field is set to the value of the last call.
func (b *BMCSpecApplyConfiguration) WithConsoleProtocol(value *ConsoleProtocolApplyConfiguration) *BMCSpecApplyConfiguration {
	b.ConsoleProtocol = value
	return b
}

// WithBMCSettingRef sets the BMCSettingRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSettingRef field is set to the value of the last call.
func (b *BMCSpecApplyConfiguration) WithBMCSettingRef(value v1.LocalObjectReference) *BMCSpecApplyConfiguration {
	b.BMCSettingRef = &value
	return b
}

// WithBMCSettingsRefs adds the given value to the BMCSettingsRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BMCSettingsRefs field.
func (b *BMCSpecApplyConfiguration) WithBMCSettingsRefs(values ...v1.LocalObjectReference) *BMCSpecApplyConfiguration {
	for i := range values {
		b.BMCSettingsRefs = append(b.BMCSettingsRefs, values[i])
	}
	return b
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *BMCSpecApplyConfiguration) WithHostname(value string) *BMCSpecApplyConfiguration {
	b.Hostname = &value
	return b
}
