// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BMCSettingsSetSpecApplyConfiguration represents a declarative configuration of the BMCSettingsSetSpec type for use
// with apply.
//
// BMCSettingsSetSpec defines the desired state of BMCSettingsSet.
type BMCSettingsSetSpecApplyConfiguration struct {
	// BMCSettingsTemplate defines the template for the BMCSettings resource to be applied to the BMCs.
	BMCSettingsTemplate *BMCSettingsTemplateApplyConfiguration `json:"bmcSettingsTemplate,omitempty"`
	// BMCSelector specifies a label selector to identify the BMCs to be selected.
	BMCSelector *v1.LabelSelectorApplyConfiguration `json:"bmcSelector,omitempty"`
}

// BMCSettingsSetSpecApplyConfiguration constructs a declarative configuration of the BMCSettingsSetSpec type for use with
// apply.
func BMCSettingsSetSpec() *BMCSettingsSetSpecApplyConfiguration {
	return &BMCSettingsSetSpecApplyConfiguration{}
}

// WithBMCSettingsTemplate sets the BMCSettingsTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSettingsTemplate field is set to the value of the last call.
func (b *BMCSettingsSetSpecApplyConfiguration) WithBMCSettingsTemplate(value *BMCSettingsTemplateApplyConfiguration) *BMCSettingsSetSpecApplyConfiguration {
	b.BMCSettingsTemplate = value
	return b
}

// WithBMCSelector sets the BMCSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSelector field is set to the value of the last call.
func (b *BMCSettingsSetSpecApplyConfiguration) WithBMCSelector(value *v1.LabelSelectorApplyConfiguration) *BMCSettingsSetSpecApplyConfiguration {
	b.BMCSelector = value
	return b
}
