// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BMCSettingsStatusApplyConfiguration represents a declarative configuration of the BMCSettingsStatus type for use
// with apply.
//
// BMCSettingsStatus defines the observed state of BMCSettings.
type BMCSettingsStatusApplyConfiguration struct {
	// State represents the current state of the BMC configuration task.
	State *apiv1alpha1.BMCSettingsState `json:"state,omitempty"`
	// FailedAttempts is the number of automatic retry attempts made after failure.
	FailedAttempts *int32 `json:"failedAttempts,omitempty"`
	// ObservedGeneration is the most recent generation observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represents the latest available observations of the BMC Settings Resource state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// BMCSettingsStatusApplyConfiguration constructs a declarative configuration of the BMCSettingsStatus type for use with
// apply.
func BMCSettingsStatus() *BMCSettingsStatusApplyConfiguration {
	return &BMCSettingsStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *BMCSettingsStatusApplyConfiguration) WithState(value apiv1alpha1.BMCSettingsState) *BMCSettingsStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithFailedAttempts sets the FailedAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedAttempts field is set to the value of the last call.
func (b *BMCSettingsStatusApplyConfiguration) WithFailedAttempts(value int32) *BMCSettingsStatusApplyConfiguration {
	b.FailedAttempts = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BMCSettingsStatusApplyConfiguration) WithObservedGeneration(value int64) *BMCSettingsStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BMCSettingsStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BMCSettingsStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
