// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BMCSettingsApplyResultEntryApplyConfiguration represents a declarative configuration of the BMCSettingsApplyResultEntry type for use
// with apply.
//
// BMCSettingsApplyResultEntry holds the URI, ETag, and value hash from the last successful apply of a single settings key.
type BMCSettingsApplyResultEntryApplyConfiguration struct {
	// URI is the Redfish resource URI from the apply response.
	URI *string `json:"uri,omitempty"`
	// ETag is the drift-detection token captured after the last successful apply.
	// Either a real ETag returned by the BMC (e.g. W/"20B77DA6") or a SHA-256
	// hash of the GET response prefixed with "hash:sha256:" for BMCs that do
	// not return ETag headers.
	ETag *string `json:"etag,omitempty"`
	// ValueHash is the SHA-256 hash of the effective (resolved) value at apply time.
	// Used to detect desired-state changes from ConfigMap/Secret rotation.
	ValueHash *string `json:"valueHash,omitempty"`
}

// BMCSettingsApplyResultEntryApplyConfiguration constructs a declarative configuration of the BMCSettingsApplyResultEntry type for use with
// apply.
func BMCSettingsApplyResultEntry() *BMCSettingsApplyResultEntryApplyConfiguration {
	return &BMCSettingsApplyResultEntryApplyConfiguration{}
}

// WithURI sets the URI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URI field is set to the value of the last call.
func (b *BMCSettingsApplyResultEntryApplyConfiguration) WithURI(value string) *BMCSettingsApplyResultEntryApplyConfiguration {
	b.URI = &value
	return b
}

// WithETag sets the ETag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ETag field is set to the value of the last call.
func (b *BMCSettingsApplyResultEntryApplyConfiguration) WithETag(value string) *BMCSettingsApplyResultEntryApplyConfiguration {
	b.ETag = &value
	return b
}

// WithValueHash sets the ValueHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValueHash field is set to the value of the last call.
func (b *BMCSettingsApplyResultEntryApplyConfiguration) WithValueHash(value string) *BMCSettingsApplyResultEntryApplyConfiguration {
	b.ValueHash = &value
	return b
}
