// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// BMCSettingsTemplateApplyConfiguration represents a declarative configuration of the BMCSettingsTemplate type for use
// with apply.
//
// BMCSettingsTemplate defines the template for BMC settings to be applied.
type BMCSettingsTemplateApplyConfiguration struct {
	// Version specifies the BMC firmware version for which the settings should be applied.
	Version *string `json:"version,omitempty"`
	// SettingsMap contains BMC settings as a map.
	SettingsMap map[string]string `json:"settings,omitempty"`
	// Variables is a list of variables that can be used in the settings for templating.
	Variables []VariableApplyConfiguration `json:"variables,omitempty"`
	// RetryPolicy defines the retry behavior for automatic retries on transient failures.
	RetryPolicy *RetryPolicyApplyConfiguration `json:"retryPolicy,omitempty"`
	// ServerMaintenancePolicy is a maintenance policy to be applied on the server.
	ServerMaintenancePolicy *apiv1alpha1.ServerMaintenancePolicy `json:"serverMaintenancePolicy,omitempty"`
}

// BMCSettingsTemplateApplyConfiguration constructs a declarative configuration of the BMCSettingsTemplate type for use with
// apply.
func BMCSettingsTemplate() *BMCSettingsTemplateApplyConfiguration {
	return &BMCSettingsTemplateApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *BMCSettingsTemplateApplyConfiguration) WithVersion(value string) *BMCSettingsTemplateApplyConfiguration {
	b.Version = &value
	return b
}

// WithSettingsMap puts the entries into the SettingsMap field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the SettingsMap field,
// overwriting an existing map entries in SettingsMap field with the same key.
func (b *BMCSettingsTemplateApplyConfiguration) WithSettingsMap(entries map[string]string) *BMCSettingsTemplateApplyConfiguration {
	if b.SettingsMap == nil && len(entries) > 0 {
		b.SettingsMap = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.SettingsMap[k] = v
	}
	return b
}

// WithVariables adds the given value to the Variables field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Variables field.
func (b *BMCSettingsTemplateApplyConfiguration) WithVariables(values ...*VariableApplyConfiguration) *BMCSettingsTemplateApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVariables")
		}
		b.Variables = append(b.Variables, *values[i])
	}
	return b
}

// WithRetryPolicy sets the RetryPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryPolicy field is set to the value of the last call.
func (b *BMCSettingsTemplateApplyConfiguration) WithRetryPolicy(value *RetryPolicyApplyConfiguration) *BMCSettingsTemplateApplyConfiguration {
	b.RetryPolicy = value
	return b
}

// WithServerMaintenancePolicy sets the ServerMaintenancePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerMaintenancePolicy field is set to the value of the last call.
func (b *BMCSettingsTemplateApplyConfiguration) WithServerMaintenancePolicy(value apiv1alpha1.ServerMaintenancePolicy) *BMCSettingsTemplateApplyConfiguration {
	b.ServerMaintenancePolicy = &value
	return b
}
