// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BMCSettingsSetStatusApplyConfiguration represents a declarative configuration of the BMCSettingsSetStatus type for use
// with apply.
//
// BMCSettingsSetStatus defines the observed state of BMCSettingsSet.
type BMCSettingsSetStatusApplyConfiguration struct {
	// FullyLabeledBMCs is the number of BMCs in the set.
	FullyLabeledBMCs *int32 `json:"fullyLabeledBMCs,omitempty"`
	// AvailableBMCSettings is the number of BMCSettings currently created by the set.
	AvailableBMCSettings *int32 `json:"availableBMCSettings,omitempty"`
	// PendingBMCSettings is the total number of pending BMCSettings in the set.
	PendingBMCSettings *int32 `json:"pendingBMCSettings,omitempty"`
	// InProgressBMCSettings is the total number of BMCSettings in the set that are currently in progress.
	InProgressBMCSettings *int32 `json:"inProgressBMCSettings,omitempty"`
	// CompletedBMCSettings is the total number of completed BMCSettings in the set.
	CompletedBMCSettings *int32 `json:"completedBMCSettings,omitempty"`
	// FailedBMCSettings is the total number of failed BMCSettings in the set.
	FailedBMCSettings *int32 `json:"failedBMCSettings,omitempty"`
}

// BMCSettingsSetStatusApplyConfiguration constructs a declarative configuration of the BMCSettingsSetStatus type for use with
// apply.
func BMCSettingsSetStatus() *BMCSettingsSetStatusApplyConfiguration {
	return &BMCSettingsSetStatusApplyConfiguration{}
}

// WithFullyLabeledBMCs sets the FullyLabeledBMCs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullyLabeledBMCs field is set to the value of the last call.
func (b *BMCSettingsSetStatusApplyConfiguration) WithFullyLabeledBMCs(value int32) *BMCSettingsSetStatusApplyConfiguration {
	b.FullyLabeledBMCs = &value
	return b
}

// WithAvailableBMCSettings sets the AvailableBMCSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableBMCSettings field is set to the value of the last call.
func (b *BMCSettingsSetStatusApplyConfiguration) WithAvailableBMCSettings(value int32) *BMCSettingsSetStatusApplyConfiguration {
	b.AvailableBMCSettings = &value
	return b
}

// WithPendingBMCSettings sets the PendingBMCSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PendingBMCSettings field is set to the value of the last call.
func (b *BMCSettingsSetStatusApplyConfiguration) WithPendingBMCSettings(value int32) *BMCSettingsSetStatusApplyConfiguration {
	b.PendingBMCSettings = &value
	return b
}

// WithInProgressBMCSettings sets the InProgressBMCSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InProgressBMCSettings field is set to the value of the last call.
func (b *BMCSettingsSetStatusApplyConfiguration) WithInProgressBMCSettings(value int32) *BMCSettingsSetStatusApplyConfiguration {
	b.InProgressBMCSettings = &value
	return b
}

// WithCompletedBMCSettings sets the CompletedBMCSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedBMCSettings field is set to the value of the last call.
func (b *BMCSettingsSetStatusApplyConfiguration) WithCompletedBMCSettings(value int32) *BMCSettingsSetStatusApplyConfiguration {
	b.CompletedBMCSettings = &value
	return b
}

// WithFailedBMCSettings sets the FailedBMCSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedBMCSettings field is set to the value of the last call.
func (b *BMCSettingsSetStatusApplyConfiguration) WithFailedBMCSettings(value int32) *BMCSettingsSetStatusApplyConfiguration {
	b.FailedBMCSettings = &value
	return b
}
