// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BMCUserSetStatusApplyConfiguration represents a declarative configuration of the BMCUserSetStatus type for use
// with apply.
//
// BMCUserSetStatus defines the observed state of BMCUserSet.
type BMCUserSetStatusApplyConfiguration struct {
	// FullyLabeledBMCs is the number of BMC in the set.
	FullyLabeledBMCs *int32 `json:"fullyLabeledBMCs,omitempty"`
	// AvailableBMCUsers is the number of BMCUsers currently created by the set.
	AvailableBMCUsers *int32 `json:"availableBMCUsers,omitempty"`
}

// BMCUserSetStatusApplyConfiguration constructs a declarative configuration of the BMCUserSetStatus type for use with
// apply.
func BMCUserSetStatus() *BMCUserSetStatusApplyConfiguration {
	return &BMCUserSetStatusApplyConfiguration{}
}

// WithFullyLabeledBMCs sets the FullyLabeledBMCs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullyLabeledBMCs field is set to the value of the last call.
func (b *BMCUserSetStatusApplyConfiguration) WithFullyLabeledBMCs(value int32) *BMCUserSetStatusApplyConfiguration {
	b.FullyLabeledBMCs = &value
	return b
}

// WithAvailableBMCUsers sets the AvailableBMCUsers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableBMCUsers field is set to the value of the last call.
func (b *BMCUserSetStatusApplyConfiguration) WithAvailableBMCUsers(value int32) *BMCUserSetStatusApplyConfiguration {
	b.AvailableBMCUsers = &value
	return b
}
