// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BMCUserSpecApplyConfiguration represents a declarative configuration of the BMCUserSpec type for use
// with apply.
//
// BMCUserSpec defines the desired state of BMCUser.
type BMCUserSpecApplyConfiguration struct {
	BMCUserTemplateApplyConfiguration `json:",inline"`
	// BMCRef references the BMC this user should be created on.
	BMCRef *v1.LocalObjectReference `json:"bmcRef,omitempty"`
}

// BMCUserSpecApplyConfiguration constructs a declarative configuration of the BMCUserSpec type for use with
// apply.
func BMCUserSpec() *BMCUserSpecApplyConfiguration {
	return &BMCUserSpecApplyConfiguration{}
}

// WithUserName sets the UserName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserName field is set to the value of the last call.
func (b *BMCUserSpecApplyConfiguration) WithUserName(value string) *BMCUserSpecApplyConfiguration {
	b.BMCUserTemplateApplyConfiguration.UserName = &value
	return b
}

// WithRoleID sets the RoleID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleID field is set to the value of the last call.
func (b *BMCUserSpecApplyConfiguration) WithRoleID(value string) *BMCUserSpecApplyConfiguration {
	b.BMCUserTemplateApplyConfiguration.RoleID = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *BMCUserSpecApplyConfiguration) WithDescription(value string) *BMCUserSpecApplyConfiguration {
	b.BMCUserTemplateApplyConfiguration.Description = &value
	return b
}

// WithRotationPeriod sets the RotationPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RotationPeriod field is set to the value of the last call.
func (b *BMCUserSpecApplyConfiguration) WithRotationPeriod(value metav1.Duration) *BMCUserSpecApplyConfiguration {
	b.BMCUserTemplateApplyConfiguration.RotationPeriod = &value
	return b
}

// WithBMCSecretRef sets the BMCSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSecretRef field is set to the value of the last call.
func (b *BMCUserSpecApplyConfiguration) WithBMCSecretRef(value v1.LocalObjectReference) *BMCUserSpecApplyConfiguration {
	b.BMCUserTemplateApplyConfiguration.BMCSecretRef = &value
	return b
}

// WithBMCRef sets the BMCRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCRef field is set to the value of the last call.
func (b *BMCUserSpecApplyConfiguration) WithBMCRef(value v1.LocalObjectReference) *BMCUserSpecApplyConfiguration {
	b.BMCRef = &value
	return b
}
