// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BMCUserStatusApplyConfiguration represents a declarative configuration of the BMCUserStatus type for use
// with apply.
//
// BMCUserStatus defines the observed state of BMCUser.
type BMCUserStatusApplyConfiguration struct {
	// EffectiveBMCSecretRef references the BMCSecret currently used for this user.
	// This may differ from Spec.BMCSecretRef if the operator generated a password.
	EffectiveBMCSecretRef *v1.LocalObjectReference `json:"effectiveBMCSecretRef,omitempty"`
	// LastRotation is the timestamp of the last password rotation.
	LastRotation *metav1.Time `json:"lastRotation,omitempty"`
	// PasswordExpiration is the timestamp when the password will expire.
	PasswordExpiration *metav1.Time `json:"passwordExpiration,omitempty"`
	// ID is the identifier of the user in the BMC system.
	ID *string `json:"id,omitempty"`
}

// BMCUserStatusApplyConfiguration constructs a declarative configuration of the BMCUserStatus type for use with
// apply.
func BMCUserStatus() *BMCUserStatusApplyConfiguration {
	return &BMCUserStatusApplyConfiguration{}
}

// WithEffectiveBMCSecretRef sets the EffectiveBMCSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EffectiveBMCSecretRef field is set to the value of the last call.
func (b *BMCUserStatusApplyConfiguration) WithEffectiveBMCSecretRef(value v1.LocalObjectReference) *BMCUserStatusApplyConfiguration {
	b.EffectiveBMCSecretRef = &value
	return b
}

// WithLastRotation sets the LastRotation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastRotation field is set to the value of the last call.
func (b *BMCUserStatusApplyConfiguration) WithLastRotation(value metav1.Time) *BMCUserStatusApplyConfiguration {
	b.LastRotation = &value
	return b
}

// WithPasswordExpiration sets the PasswordExpiration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PasswordExpiration field is set to the value of the last call.
func (b *BMCUserStatusApplyConfiguration) WithPasswordExpiration(value metav1.Time) *BMCUserStatusApplyConfiguration {
	b.PasswordExpiration = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *BMCUserStatusApplyConfiguration) WithID(value string) *BMCUserStatusApplyConfiguration {
	b.ID = &value
	return b
}
