// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BMCUserSetSpecApplyConfiguration represents a declarative configuration of the BMCUserSetSpec type for use
// with apply.
//
// BMCUserSetSpec defines the desired state of BMCUserSet.
type BMCUserSetSpecApplyConfiguration struct {
	// BMCSelector specifies a label selector to identify the BMCs that are to be selected.
	BMCSelector *v1.LabelSelectorApplyConfiguration `json:"bmcSelector,omitempty"`
	// BMCUserTemplate defines the template for the BMCUser Resource to be applied to the BMCs.
	BMCUserTemplate *BMCUserTemplateApplyConfiguration `json:"bmcUserTemplate,omitempty"`
}

// BMCUserSetSpecApplyConfiguration constructs a declarative configuration of the BMCUserSetSpec type for use with
// apply.
func BMCUserSetSpec() *BMCUserSetSpecApplyConfiguration {
	return &BMCUserSetSpecApplyConfiguration{}
}

// WithBMCSelector sets the BMCSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSelector field is set to the value of the last call.
func (b *BMCUserSetSpecApplyConfiguration) WithBMCSelector(value *v1.LabelSelectorApplyConfiguration) *BMCUserSetSpecApplyConfiguration {
	b.BMCSelector = value
	return b
}

// WithBMCUserTemplate sets the BMCUserTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCUserTemplate field is set to the value of the last call.
func (b *BMCUserSetSpecApplyConfiguration) WithBMCUserTemplate(value *BMCUserTemplateApplyConfiguration) *BMCUserSetSpecApplyConfiguration {
	b.BMCUserTemplate = value
	return b
}
