// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BMCUserTemplateApplyConfiguration represents a declarative configuration of the BMCUserTemplate type for use
// with apply.
//
// BMCUserTemplate defines the template for the BMCUser Resource to be applied to the BMCs.
type BMCUserTemplateApplyConfiguration struct {
	// Username of the BMC user.
	UserName *string `json:"userName,omitempty"`
	// RoleID is the ID of the role to assign to the user.
	// The available roles depend on the BMC implementation.
	// For Redfish, common role IDs are "Administrator", "Operator", "ReadOnly".
	RoleID *string `json:"roleID,omitempty"`
	// Description is an optional description for the BMC user.
	Description *string `json:"description,omitempty"`
	// RotationPeriod defines how often the password should be rotated.
	// if not set, the password will not be rotated.
	RotationPeriod *v1.Duration `json:"rotationPeriod,omitempty"`
	// BMCSecretRef references the BMCSecret containing the credentials for this user.
	// If not set, the operator will generate a secure password based on BMC manufacturer requirements.
	BMCSecretRef *corev1.LocalObjectReference `json:"bmcSecretRef,omitempty"`
}

// BMCUserTemplateApplyConfiguration constructs a declarative configuration of the BMCUserTemplate type for use with
// apply.
func BMCUserTemplate() *BMCUserTemplateApplyConfiguration {
	return &BMCUserTemplateApplyConfiguration{}
}

// WithUserName sets the UserName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserName field is set to the value of the last call.
func (b *BMCUserTemplateApplyConfiguration) WithUserName(value string) *BMCUserTemplateApplyConfiguration {
	b.UserName = &value
	return b
}

// WithRoleID sets the RoleID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleID field is set to the value of the last call.
func (b *BMCUserTemplateApplyConfiguration) WithRoleID(value string) *BMCUserTemplateApplyConfiguration {
	b.RoleID = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *BMCUserTemplateApplyConfiguration) WithDescription(value string) *BMCUserTemplateApplyConfiguration {
	b.Description = &value
	return b
}

// WithRotationPeriod sets the RotationPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RotationPeriod field is set to the value of the last call.
func (b *BMCUserTemplateApplyConfiguration) WithRotationPeriod(value v1.Duration) *BMCUserTemplateApplyConfiguration {
	b.RotationPeriod = &value
	return b
}

// WithBMCSecretRef sets the BMCSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCSecretRef field is set to the value of the last call.
func (b *BMCUserTemplateApplyConfiguration) WithBMCSecretRef(value corev1.LocalObjectReference) *BMCUserTemplateApplyConfiguration {
	b.BMCSecretRef = &value
	return b
}
