// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// BMCVersionTemplateApplyConfiguration represents a declarative configuration of the BMCVersionTemplate type for use
// with apply.
type BMCVersionTemplateApplyConfiguration struct {
	// Version specifies the BMC version to upgrade to.
	Version *string `json:"version,omitempty"`
	// UpdatePolicy indicates whether the server's upgrade service should bypass vendor update policies.
	UpdatePolicy *apiv1alpha1.UpdatePolicy `json:"updatePolicy,omitempty"`
	// Image specifies the image to use to upgrade to the given BMC version.
	Image *ImageSpecApplyConfiguration `json:"image,omitempty"`
	// RetryPolicy defines the retry behavior for automatic retries on transient failures.
	RetryPolicy *RetryPolicyApplyConfiguration `json:"retryPolicy,omitempty"`
	// ServerMaintenancePolicy is a maintenance policy to be enforced on the server managed by referred BMC.
	ServerMaintenancePolicy *apiv1alpha1.ServerMaintenancePolicy `json:"serverMaintenancePolicy,omitempty"`
}

// BMCVersionTemplateApplyConfiguration constructs a declarative configuration of the BMCVersionTemplate type for use with
// apply.
func BMCVersionTemplate() *BMCVersionTemplateApplyConfiguration {
	return &BMCVersionTemplateApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *BMCVersionTemplateApplyConfiguration) WithVersion(value string) *BMCVersionTemplateApplyConfiguration {
	b.Version = &value
	return b
}

// WithUpdatePolicy sets the UpdatePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatePolicy field is set to the value of the last call.
func (b *BMCVersionTemplateApplyConfiguration) WithUpdatePolicy(value apiv1alpha1.UpdatePolicy) *BMCVersionTemplateApplyConfiguration {
	b.UpdatePolicy = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *BMCVersionTemplateApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *BMCVersionTemplateApplyConfiguration {
	b.Image = value
	return b
}

// WithRetryPolicy sets the RetryPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryPolicy field is set to the value of the last call.
func (b *BMCVersionTemplateApplyConfiguration) WithRetryPolicy(value *RetryPolicyApplyConfiguration) *BMCVersionTemplateApplyConfiguration {
	b.RetryPolicy = value
	return b
}

// WithServerMaintenancePolicy sets the ServerMaintenancePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerMaintenancePolicy field is set to the value of the last call.
func (b *BMCVersionTemplateApplyConfiguration) WithServerMaintenancePolicy(value apiv1alpha1.ServerMaintenancePolicy) *BMCVersionTemplateApplyConfiguration {
	b.ServerMaintenancePolicy = &value
	return b
}
