// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BMCVersionSetStatusApplyConfiguration represents a declarative configuration of the BMCVersionSetStatus type for use
// with apply.
//
// BMCVersionSetStatus defines the observed state of BMCVersionSet.
type BMCVersionSetStatusApplyConfiguration struct {
	// FullyLabeledBMCs is the number of BMCs in the set.
	FullyLabeledBMCs *int32 `json:"fullyLabeledBMCs,omitempty"`
	// AvailableBMCVersion is the number of BMCVersion resources currently created by the set.
	AvailableBMCVersion *int32 `json:"availableBMCVersion,omitempty"`
	// PendingBMCVersion is the total number of pending BMCVersion resources in the set.
	PendingBMCVersion *int32 `json:"pendingBMCVersion,omitempty"`
	// InProgressBMCVersion is the total number of BMCVersion resources in the set that are currently in progress.
	InProgressBMCVersion *int32 `json:"inProgressBMCVersion,omitempty"`
	// CompletedBMCVersion is the total number of completed BMCVersion resources in the set.
	CompletedBMCVersion *int32 `json:"completedBMCVersion,omitempty"`
	// FailedBMCVersion is the total number of failed BMCVersion resources in the set.
	FailedBMCVersion *int32 `json:"failedBMCVersion,omitempty"`
}

// BMCVersionSetStatusApplyConfiguration constructs a declarative configuration of the BMCVersionSetStatus type for use with
// apply.
func BMCVersionSetStatus() *BMCVersionSetStatusApplyConfiguration {
	return &BMCVersionSetStatusApplyConfiguration{}
}

// WithFullyLabeledBMCs sets the FullyLabeledBMCs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullyLabeledBMCs field is set to the value of the last call.
func (b *BMCVersionSetStatusApplyConfiguration) WithFullyLabeledBMCs(value int32) *BMCVersionSetStatusApplyConfiguration {
	b.FullyLabeledBMCs = &value
	return b
}

// WithAvailableBMCVersion sets the AvailableBMCVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableBMCVersion field is set to the value of the last call.
func (b *BMCVersionSetStatusApplyConfiguration) WithAvailableBMCVersion(value int32) *BMCVersionSetStatusApplyConfiguration {
	b.AvailableBMCVersion = &value
	return b
}

// WithPendingBMCVersion sets the PendingBMCVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PendingBMCVersion field is set to the value of the last call.
func (b *BMCVersionSetStatusApplyConfiguration) WithPendingBMCVersion(value int32) *BMCVersionSetStatusApplyConfiguration {
	b.PendingBMCVersion = &value
	return b
}

// WithInProgressBMCVersion sets the InProgressBMCVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InProgressBMCVersion field is set to the value of the last call.
func (b *BMCVersionSetStatusApplyConfiguration) WithInProgressBMCVersion(value int32) *BMCVersionSetStatusApplyConfiguration {
	b.InProgressBMCVersion = &value
	return b
}

// WithCompletedBMCVersion sets the CompletedBMCVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedBMCVersion field is set to the value of the last call.
func (b *BMCVersionSetStatusApplyConfiguration) WithCompletedBMCVersion(value int32) *BMCVersionSetStatusApplyConfiguration {
	b.CompletedBMCVersion = &value
	return b
}

// WithFailedBMCVersion sets the FailedBMCVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedBMCVersion field is set to the value of the last call.
func (b *BMCVersionSetStatusApplyConfiguration) WithFailedBMCVersion(value int32) *BMCVersionSetStatusApplyConfiguration {
	b.FailedBMCVersion = &value
	return b
}
