// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BMCVersionStatusApplyConfiguration represents a declarative configuration of the BMCVersionStatus type for use
// with apply.
//
// BMCVersionStatus defines the observed state of BMCVersion.
type BMCVersionStatusApplyConfiguration struct {
	// State represents the current state of the BMC configuration task.
	State *apiv1alpha1.BMCVersionState `json:"state,omitempty"`
	// UpgradeTask contains the state of the upgrade task created by the BMC.
	UpgradeTask *TaskApplyConfiguration `json:"upgradeTask,omitempty"`
	// Conditions represents the latest available observations of the BMC version upgrade state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// BMCVersionStatusApplyConfiguration constructs a declarative configuration of the BMCVersionStatus type for use with
// apply.
func BMCVersionStatus() *BMCVersionStatusApplyConfiguration {
	return &BMCVersionStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *BMCVersionStatusApplyConfiguration) WithState(value apiv1alpha1.BMCVersionState) *BMCVersionStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithUpgradeTask sets the UpgradeTask field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpgradeTask field is set to the value of the last call.
func (b *BMCVersionStatusApplyConfiguration) WithUpgradeTask(value *TaskApplyConfiguration) *BMCVersionStatusApplyConfiguration {
	b.UpgradeTask = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BMCVersionStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BMCVersionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
