// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// BMCVersionSpecApplyConfiguration represents a declarative configuration of the BMCVersionSpec type for use
// with apply.
//
// BMCVersionSpec defines the desired state of BMCVersion.
type BMCVersionSpecApplyConfiguration struct {
	// BMCVersionTemplate defines the template for BMC version to be applied on the server's BMC.
	BMCVersionTemplateApplyConfiguration `json:",inline"`
	// ServerMaintenanceRefs are references to ServerMaintenance objects that the controller has requested for the related servers.
	ServerMaintenanceRefs []ObjectReferenceApplyConfiguration `json:"serverMaintenanceRefs,omitempty"`
	// BMCRef is a reference to a specific BMC to apply BMC upgrade on.
	BMCRef *v1.LocalObjectReference `json:"bmcRef,omitempty"`
}

// BMCVersionSpecApplyConfiguration constructs a declarative configuration of the BMCVersionSpec type for use with
// apply.
func BMCVersionSpec() *BMCVersionSpecApplyConfiguration {
	return &BMCVersionSpecApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *BMCVersionSpecApplyConfiguration) WithVersion(value string) *BMCVersionSpecApplyConfiguration {
	b.BMCVersionTemplateApplyConfiguration.Version = &value
	return b
}

// WithUpdatePolicy sets the UpdatePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatePolicy field is set to the value of the last call.
func (b *BMCVersionSpecApplyConfiguration) WithUpdatePolicy(value apiv1alpha1.UpdatePolicy) *BMCVersionSpecApplyConfiguration {
	b.BMCVersionTemplateApplyConfiguration.UpdatePolicy = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *BMCVersionSpecApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *BMCVersionSpecApplyConfiguration {
	b.BMCVersionTemplateApplyConfiguration.Image = value
	return b
}

// WithRetryPolicy sets the RetryPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryPolicy field is set to the value of the last call.
func (b *BMCVersionSpecApplyConfiguration) WithRetryPolicy(value *RetryPolicyApplyConfiguration) *BMCVersionSpecApplyConfiguration {
	b.BMCVersionTemplateApplyConfiguration.RetryPolicy = value
	return b
}

// WithServerMaintenancePolicy sets the ServerMaintenancePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerMaintenancePolicy field is set to the value of the last call.
func (b *BMCVersionSpecApplyConfiguration) WithServerMaintenancePolicy(value apiv1alpha1.ServerMaintenancePolicy) *BMCVersionSpecApplyConfiguration {
	b.BMCVersionTemplateApplyConfiguration.ServerMaintenancePolicy = &value
	return b
}

// WithServerMaintenanceRefs adds the given value to the ServerMaintenanceRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServerMaintenanceRefs field.
func (b *BMCVersionSpecApplyConfiguration) WithServerMaintenanceRefs(values ...*ObjectReferenceApplyConfiguration) *BMCVersionSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithServerMaintenanceRefs")
		}
		b.ServerMaintenanceRefs = append(b.ServerMaintenanceRefs, *values[i])
	}
	return b
}

// WithBMCRef sets the BMCRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCRef field is set to the value of the last call.
func (b *BMCVersionSpecApplyConfiguration) WithBMCRef(value v1.LocalObjectReference) *BMCVersionSpecApplyConfiguration {
	b.BMCRef = &value
	return b
}
