// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BootOrderApplyConfiguration represents a declarative configuration of the BootOrder type for use
// with apply.
//
// BootOrder represents the boot order of the server.
type BootOrderApplyConfiguration struct {
	// Name is the name of the boot device.
	Name *string `json:"name,omitempty"`
	// Priority is the priority of the boot device.
	Priority *int `json:"priority,omitempty"`
	// Device is the device to boot from.
	Device *string `json:"device,omitempty"`
}

// BootOrderApplyConfiguration constructs a declarative configuration of the BootOrder type for use with
// apply.
func BootOrder() *BootOrderApplyConfiguration {
	return &BootOrderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BootOrderApplyConfiguration) WithName(value string) *BootOrderApplyConfiguration {
	b.Name = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *BootOrderApplyConfiguration) WithPriority(value int) *BootOrderApplyConfiguration {
	b.Priority = &value
	return b
}

// WithDevice sets the Device field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Device field is set to the value of the last call.
func (b *BootOrderApplyConfiguration) WithDevice(value string) *BootOrderApplyConfiguration {
	b.Device = &value
	return b
}
