// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DiskCleaningStatusApplyConfiguration represents a declarative configuration of the DiskCleaningStatus type for use
// with apply.
//
// DiskCleaningStatus represents the status of disk cleaning operations.
type DiskCleaningStatusApplyConfiguration struct {
	LastCleanedAt  *v1.Time                      `json:"lastCleanedAt,omitempty"`
	DisksProcessed *int                          `json:"disksProcessed,omitempty"`
	CleaningMode   *apiv1alpha1.DiskCleaningMode `json:"cleaningMode,omitempty"`
	Message        *string                       `json:"message,omitempty"`
}

// DiskCleaningStatusApplyConfiguration constructs a declarative configuration of the DiskCleaningStatus type for use with
// apply.
func DiskCleaningStatus() *DiskCleaningStatusApplyConfiguration {
	return &DiskCleaningStatusApplyConfiguration{}
}

// WithLastCleanedAt sets the LastCleanedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastCleanedAt field is set to the value of the last call.
func (b *DiskCleaningStatusApplyConfiguration) WithLastCleanedAt(value v1.Time) *DiskCleaningStatusApplyConfiguration {
	b.LastCleanedAt = &value
	return b
}

// WithDisksProcessed sets the DisksProcessed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisksProcessed field is set to the value of the last call.
func (b *DiskCleaningStatusApplyConfiguration) WithDisksProcessed(value int) *DiskCleaningStatusApplyConfiguration {
	b.DisksProcessed = &value
	return b
}

// WithCleaningMode sets the CleaningMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CleaningMode field is set to the value of the last call.
func (b *DiskCleaningStatusApplyConfiguration) WithCleaningMode(value apiv1alpha1.DiskCleaningMode) *DiskCleaningStatusApplyConfiguration {
	b.CleaningMode = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *DiskCleaningStatusApplyConfiguration) WithMessage(value string) *DiskCleaningStatusApplyConfiguration {
	b.Message = &value
	return b
}
