// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DynamicSettingApplyConfiguration represents a declarative configuration of the DynamicSetting type for use
// with apply.
type DynamicSettingApplyConfiguration struct {
	// Key is the BMC setting key to set.
	Key *string `json:"key,omitempty"`
	// ValueFrom defines a simple single source for the setting value.
	ValueFrom *DynamicSettingSourceApplyConfiguration `json:"valueFrom,omitempty"`
	// Format defines a composite setting format with placeholders like $(name).
	Format *string `json:"format,omitempty"`
	// Variables maps format placeholder names to their sources.
	Variables map[string]DynamicSettingSourceApplyConfiguration `json:"variables,omitempty"`
}

// DynamicSettingApplyConfiguration constructs a declarative configuration of the DynamicSetting type for use with
// apply.
func DynamicSetting() *DynamicSettingApplyConfiguration {
	return &DynamicSettingApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *DynamicSettingApplyConfiguration) WithKey(value string) *DynamicSettingApplyConfiguration {
	b.Key = &value
	return b
}

// WithValueFrom sets the ValueFrom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValueFrom field is set to the value of the last call.
func (b *DynamicSettingApplyConfiguration) WithValueFrom(value *DynamicSettingSourceApplyConfiguration) *DynamicSettingApplyConfiguration {
	b.ValueFrom = value
	return b
}

// WithFormat sets the Format field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Format field is set to the value of the last call.
func (b *DynamicSettingApplyConfiguration) WithFormat(value string) *DynamicSettingApplyConfiguration {
	b.Format = &value
	return b
}

// WithVariables puts the entries into the Variables field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Variables field,
// overwriting an existing map entries in Variables field with the same key.
func (b *DynamicSettingApplyConfiguration) WithVariables(entries map[string]DynamicSettingSourceApplyConfiguration) *DynamicSettingApplyConfiguration {
	if b.Variables == nil && len(entries) > 0 {
		b.Variables = make(map[string]DynamicSettingSourceApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Variables[k] = v
	}
	return b
}
