// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// FieldRefSelectorApplyConfiguration represents a declarative configuration of the FieldRefSelector type for use
// with apply.
type FieldRefSelectorApplyConfiguration struct {
	// FieldPath is the path of the field on the BMCSettings object to select (e.g. spec.BMCRef.name).
	// Only string-typed fields are supported; integer, bool, or map fields will cause a resolution error.
	FieldPath *string `json:"fieldPath,omitempty"`
}

// FieldRefSelectorApplyConfiguration constructs a declarative configuration of the FieldRefSelector type for use with
// apply.
func FieldRefSelector() *FieldRefSelectorApplyConfiguration {
	return &FieldRefSelectorApplyConfiguration{}
}

// WithFieldPath sets the FieldPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldPath field is set to the value of the last call.
func (b *FieldRefSelectorApplyConfiguration) WithFieldPath(value string) *FieldRefSelectorApplyConfiguration {
	b.FieldPath = &value
	return b
}
