// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HardwareTelemetryProfileStatusApplyConfiguration represents a declarative configuration of the HardwareTelemetryProfileStatus type for use
// with apply.
//
// HardwareTelemetryProfileStatus defines the observed state of HardwareTelemetryProfile.
type HardwareTelemetryProfileStatusApplyConfiguration struct {
	// Conditions holds the conditions for the HardwareTelemetryProfile.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// AppliedNodes lists the per-BMC status for every node currently matched by this profile.
	AppliedNodes []AppliedNodeStatusApplyConfiguration `json:"appliedNodes,omitempty"`
}

// HardwareTelemetryProfileStatusApplyConfiguration constructs a declarative configuration of the HardwareTelemetryProfileStatus type for use with
// apply.
func HardwareTelemetryProfileStatus() *HardwareTelemetryProfileStatusApplyConfiguration {
	return &HardwareTelemetryProfileStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *HardwareTelemetryProfileStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *HardwareTelemetryProfileStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithAppliedNodes adds the given value to the AppliedNodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AppliedNodes field.
func (b *HardwareTelemetryProfileStatusApplyConfiguration) WithAppliedNodes(values ...*AppliedNodeStatusApplyConfiguration) *HardwareTelemetryProfileStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAppliedNodes")
		}
		b.AppliedNodes = append(b.AppliedNodes, *values[i])
	}
	return b
}
