// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ImageSpecApplyConfiguration represents a declarative configuration of the ImageSpec type for use
// with apply.
type ImageSpecApplyConfiguration struct {
	// SecretRef is a reference to the Secret containing the credentials to access the image URI.
	SecretRef *v1.SecretReference `json:"secretRef,omitempty"`
	// TransferProtocol is the network protocol used to retrieve the image URI.
	TransferProtocol *string `json:"transferProtocol,omitempty"`
	// URI is the URI of the software image to install.
	URI *string `json:"URI,omitempty"`
}

// ImageSpecApplyConfiguration constructs a declarative configuration of the ImageSpec type for use with
// apply.
func ImageSpec() *ImageSpecApplyConfiguration {
	return &ImageSpecApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithSecretRef(value v1.SecretReference) *ImageSpecApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithTransferProtocol sets the TransferProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TransferProtocol field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithTransferProtocol(value string) *ImageSpecApplyConfiguration {
	b.TransferProtocol = &value
	return b
}

// WithURI sets the URI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URI field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithURI(value string) *ImageSpecApplyConfiguration {
	b.URI = &value
	return b
}
