// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ImmutableObjectReferenceApplyConfiguration represents a declarative configuration of the ImmutableObjectReference type for use
// with apply.
//
// ImmutableObjectReference is a namespaced name reference whose name and namespace
// cannot be changed once set (the entire reference can still be set or cleared).
type ImmutableObjectReferenceApplyConfiguration struct {
	// Namespace is the namespace of the referenced object.
	Namespace *string `json:"namespace,omitempty"`
	// Name is the name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// ImmutableObjectReferenceApplyConfiguration constructs a declarative configuration of the ImmutableObjectReference type for use with
// apply.
func ImmutableObjectReference() *ImmutableObjectReferenceApplyConfiguration {
	return &ImmutableObjectReferenceApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ImmutableObjectReferenceApplyConfiguration) WithNamespace(value string) *ImmutableObjectReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ImmutableObjectReferenceApplyConfiguration) WithName(value string) *ImmutableObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}
