// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// InlineEndpointApplyConfiguration represents a declarative configuration of the InlineEndpoint type for use
// with apply.
//
// InlineEndpoint defines inline network access configuration for the BMC.
type InlineEndpointApplyConfiguration struct {
	// MACAddress is the MAC address of the endpoint.
	MACAddress *string `json:"macAddress,omitempty"`
	// IP is the IP address of the BMC.
	IP *apiv1alpha1.IP `json:"ip,omitempty"`
}

// InlineEndpointApplyConfiguration constructs a declarative configuration of the InlineEndpoint type for use with
// apply.
func InlineEndpoint() *InlineEndpointApplyConfiguration {
	return &InlineEndpointApplyConfiguration{}
}

// WithMACAddress sets the MACAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MACAddress field is set to the value of the last call.
func (b *InlineEndpointApplyConfiguration) WithMACAddress(value string) *InlineEndpointApplyConfiguration {
	b.MACAddress = &value
	return b
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *InlineEndpointApplyConfiguration) WithIP(value apiv1alpha1.IP) *InlineEndpointApplyConfiguration {
	b.IP = &value
	return b
}
