// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LLDPNeighborApplyConfiguration represents a declarative configuration of the LLDPNeighbor type for use
// with apply.
//
// LLDPNeighbor defines the details of an LLDP neighbor.
type LLDPNeighborApplyConfiguration struct {
	// MACAddress is the MAC address of the LLDP neighbor.
	MACAddress *string `json:"macAddress,omitempty"`
	// PortID is the port identifier of the LLDP neighbor.
	PortID *string `json:"portID,omitempty"`
	// PortDescription is the port description of the LLDP neighbor.
	PortDescription *string `json:"portDescription,omitempty"`
	// SystemName is the system name of the LLDP neighbor.
	SystemName *string `json:"systemName,omitempty"`
	// SystemDescription is the system description of the LLDP neighbor.
	SystemDescription *string `json:"systemDescription,omitempty"`
}

// LLDPNeighborApplyConfiguration constructs a declarative configuration of the LLDPNeighbor type for use with
// apply.
func LLDPNeighbor() *LLDPNeighborApplyConfiguration {
	return &LLDPNeighborApplyConfiguration{}
}

// WithMACAddress sets the MACAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MACAddress field is set to the value of the last call.
func (b *LLDPNeighborApplyConfiguration) WithMACAddress(value string) *LLDPNeighborApplyConfiguration {
	b.MACAddress = &value
	return b
}

// WithPortID sets the PortID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortID field is set to the value of the last call.
func (b *LLDPNeighborApplyConfiguration) WithPortID(value string) *LLDPNeighborApplyConfiguration {
	b.PortID = &value
	return b
}

// WithPortDescription sets the PortDescription field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortDescription field is set to the value of the last call.
func (b *LLDPNeighborApplyConfiguration) WithPortDescription(value string) *LLDPNeighborApplyConfiguration {
	b.PortDescription = &value
	return b
}

// WithSystemName sets the SystemName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemName field is set to the value of the last call.
func (b *LLDPNeighborApplyConfiguration) WithSystemName(value string) *LLDPNeighborApplyConfiguration {
	b.SystemName = &value
	return b
}

// WithSystemDescription sets the SystemDescription field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemDescription field is set to the value of the last call.
func (b *LLDPNeighborApplyConfiguration) WithSystemDescription(value string) *LLDPNeighborApplyConfiguration {
	b.SystemDescription = &value
	return b
}
