// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// NetworkInterfaceApplyConfiguration represents a declarative configuration of the NetworkInterface type for use
// with apply.
//
// NetworkInterface defines the details of a network interface.
type NetworkInterfaceApplyConfiguration struct {
	// Name is the name of the network interface.
	Name *string `json:"name,omitempty"`
	// IP is the IP address assigned to the network interface.
	// Deprecated: Use IPs instead. Kept for backward compatibility, always nil.
	IP *apiv1alpha1.IP `json:"ip,omitempty"`
	// IPs is a list of IP addresses (both IPv4 and IPv6) assigned to the network interface.
	IPs []apiv1alpha1.IP `json:"ips,omitempty"`
	// MACAddress is the MAC address of the network interface.
	MACAddress *string `json:"macAddress,omitempty"`
	// CarrierStatus is the operational carrier status of the network interface.
	CarrierStatus *string `json:"carrierStatus,omitempty"`
	// PCIAddress is the PCI bus address of the underlying NIC (e.g. "0000:01:00.0").
	PCIAddress *string `json:"pciAddress,omitempty"`
	// Speed is the link speed reported by the NIC driver.
	Speed *string `json:"speed,omitempty"`
	// LinkModes is the list of link modes supported by the NIC.
	LinkModes []string `json:"linkModes,omitempty"`
	// SupportedPorts is the list of port types supported by the NIC (e.g. TP, FIBRE).
	SupportedPorts []string `json:"supportedPorts,omitempty"`
	// FirmwareVersion is the firmware version reported by the NIC driver.
	FirmwareVersion *string `json:"firmwareVersion,omitempty"`
	// Neighbors contains the LLDP neighbors discovered on this interface.
	Neighbors []LLDPNeighborApplyConfiguration `json:"neighbors,omitempty"`
}

// NetworkInterfaceApplyConfiguration constructs a declarative configuration of the NetworkInterface type for use with
// apply.
func NetworkInterface() *NetworkInterfaceApplyConfiguration {
	return &NetworkInterfaceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NetworkInterfaceApplyConfiguration) WithName(value string) *NetworkInterfaceApplyConfiguration {
	b.Name = &value
	return b
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *NetworkInterfaceApplyConfiguration) WithIP(value apiv1alpha1.IP) *NetworkInterfaceApplyConfiguration {
	b.IP = &value
	return b
}

// WithIPs adds the given value to the IPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPs field.
func (b *NetworkInterfaceApplyConfiguration) WithIPs(values ...apiv1alpha1.IP) *NetworkInterfaceApplyConfiguration {
	for i := range values {
		b.IPs = append(b.IPs, values[i])
	}
	return b
}

// WithMACAddress sets the MACAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MACAddress field is set to the value of the last call.
func (b *NetworkInterfaceApplyConfiguration) WithMACAddress(value string) *NetworkInterfaceApplyConfiguration {
	b.MACAddress = &value
	return b
}

// WithCarrierStatus sets the CarrierStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CarrierStatus field is set to the value of the last call.
func (b *NetworkInterfaceApplyConfiguration) WithCarrierStatus(value string) *NetworkInterfaceApplyConfiguration {
	b.CarrierStatus = &value
	return b
}

// WithPCIAddress sets the PCIAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PCIAddress field is set to the value of the last call.
func (b *NetworkInterfaceApplyConfiguration) WithPCIAddress(value string) *NetworkInterfaceApplyConfiguration {
	b.PCIAddress = &value
	return b
}

// WithSpeed sets the Speed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Speed field is set to the value of the last call.
func (b *NetworkInterfaceApplyConfiguration) WithSpeed(value string) *NetworkInterfaceApplyConfiguration {
	b.Speed = &value
	return b
}

// WithLinkModes adds the given value to the LinkModes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LinkModes field.
func (b *NetworkInterfaceApplyConfiguration) WithLinkModes(values ...string) *NetworkInterfaceApplyConfiguration {
	for i := range values {
		b.LinkModes = append(b.LinkModes, values[i])
	}
	return b
}

// WithSupportedPorts adds the given value to the SupportedPorts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SupportedPorts field.
func (b *NetworkInterfaceApplyConfiguration) WithSupportedPorts(values ...string) *NetworkInterfaceApplyConfiguration {
	for i := range values {
		b.SupportedPorts = append(b.SupportedPorts, values[i])
	}
	return b
}

// WithFirmwareVersion sets the FirmwareVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirmwareVersion field is set to the value of the last call.
func (b *NetworkInterfaceApplyConfiguration) WithFirmwareVersion(value string) *NetworkInterfaceApplyConfiguration {
	b.FirmwareVersion = &value
	return b
}

// WithNeighbors adds the given value to the Neighbors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Neighbors field.
func (b *NetworkInterfaceApplyConfiguration) WithNeighbors(values ...*LLDPNeighborApplyConfiguration) *NetworkInterfaceApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNeighbors")
		}
		b.Neighbors = append(b.Neighbors, *values[i])
	}
	return b
}
