// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// ProtocolApplyConfiguration represents a declarative configuration of the Protocol type for use
// with apply.
//
// Protocol defines the protocol and port used for communicating with the BMC.
type ProtocolApplyConfiguration struct {
	// Name specifies the name of the protocol.
	Name *apiv1alpha1.ProtocolName `json:"name,omitempty"`
	// Port specifies the port number used for communication.
	Port *int32 `json:"port,omitempty"`
	// Scheme specifies the scheme used for communication.
	Scheme *apiv1alpha1.ProtocolScheme `json:"scheme,omitempty"`
}

// ProtocolApplyConfiguration constructs a declarative configuration of the Protocol type for use with
// apply.
func Protocol() *ProtocolApplyConfiguration {
	return &ProtocolApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ProtocolApplyConfiguration) WithName(value apiv1alpha1.ProtocolName) *ProtocolApplyConfiguration {
	b.Name = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ProtocolApplyConfiguration) WithPort(value int32) *ProtocolApplyConfiguration {
	b.Port = &value
	return b
}

// WithScheme sets the Scheme field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scheme field is set to the value of the last call.
func (b *ProtocolApplyConfiguration) WithScheme(value apiv1alpha1.ProtocolScheme) *ProtocolApplyConfiguration {
	b.Scheme = &value
	return b
}
