// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RetryPolicyApplyConfiguration represents a declarative configuration of the RetryPolicy type for use
// with apply.
//
// RetryPolicy defines the retry behavior on transient failures.
type RetryPolicyApplyConfiguration struct {
	// MaxAttempts is the maximum number of automatic retry attempts after failure.
	// 0 means no automatic retries. Must be between 0 and 10 inclusive.
	// If not set, the operator-level default is used.
	MaxAttempts *int32 `json:"maxAttempts,omitempty"`
}

// RetryPolicyApplyConfiguration constructs a declarative configuration of the RetryPolicy type for use with
// apply.
func RetryPolicy() *RetryPolicyApplyConfiguration {
	return &RetryPolicyApplyConfiguration{}
}

// WithMaxAttempts sets the MaxAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAttempts field is set to the value of the last call.
func (b *RetryPolicyApplyConfiguration) WithMaxAttempts(value int32) *RetryPolicyApplyConfiguration {
	b.MaxAttempts = &value
	return b
}
