// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ServerStatusApplyConfiguration represents a declarative configuration of the ServerStatus type for use
// with apply.
//
// ServerStatus defines the observed state of Server.
type ServerStatusApplyConfiguration struct {
	// Manufacturer is the name of the server manufacturer.
	Manufacturer *string `json:"manufacturer,omitempty"`
	// BIOSVersion is the version of the server's BIOS.
	BIOSVersion *string `json:"biosVersion,omitempty"`
	// Model is the model of the server.
	Model *string `json:"model,omitempty"`
	// SKU is the stock keeping unit identifier for the server.
	SKU *string `json:"sku,omitempty"`
	// SerialNumber is the serial number of the server.
	SerialNumber *string `json:"serialNumber,omitempty"`
	// PowerState represents the current power state of the server.
	PowerState *apiv1alpha1.ServerPowerState `json:"powerState,omitempty"`
	// IndicatorLED specifies the current state of the server's indicator LED.
	IndicatorLED *apiv1alpha1.IndicatorLED `json:"indicatorLED,omitempty"`
	// State represents the current state of the server.
	State *apiv1alpha1.ServerState `json:"state,omitempty"`
	// NetworkInterfaces is a list of network interfaces associated with the server.
	NetworkInterfaces []NetworkInterfaceApplyConfiguration `json:"networkInterfaces,omitempty"`
	// TotalSystemMemory is the total amount of memory in bytes available on the server.
	TotalSystemMemory *resource.Quantity `json:"totalSystemMemory,omitempty"`
	// Processors is a list of Processors associated with the server.
	Processors []ProcessorApplyConfiguration `json:"processors,omitempty"`
	// Storages is a list of storages associated with the server.
	Storages []StorageApplyConfiguration `json:"storages,omitempty"`
	// Conditions represents the latest available observations of the server's current state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ServerStatusApplyConfiguration constructs a declarative configuration of the ServerStatus type for use with
// apply.
func ServerStatus() *ServerStatusApplyConfiguration {
	return &ServerStatusApplyConfiguration{}
}

// WithManufacturer sets the Manufacturer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manufacturer field is set to the value of the last call.
func (b *ServerStatusApplyConfiguration) WithManufacturer(value string) *ServerStatusApplyConfiguration {
	b.Manufacturer = &value
	return b
}

// WithBIOSVersion sets the BIOSVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BIOSVersion field is set to the value of the last call.
func (b *ServerStatusApplyConfiguration) WithBIOSVersion(value string) *ServerStatusApplyConfiguration {
	b.BIOSVersion = &value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *ServerStatusApplyConfiguration) WithModel(value string) *ServerStatusApplyConfiguration {
	b.Model = &value
	return b
}

// WithSKU sets the SKU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SKU field is set to the value of the last call.
func (b *ServerStatusApplyConfiguration) WithSKU(value string) *ServerStatusApplyConfiguration {
	b.SKU = &value
	return b
}

// WithSerialNumber sets the SerialNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SerialNumber field is set to the value of the last call.
func (b *ServerStatusApplyConfiguration) WithSerialNumber(value string) *ServerStatusApplyConfiguration {
	b.SerialNumber = &value
	return b
}

// WithPowerState sets the PowerState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PowerState field is set to the value of the last call.
func (b *ServerStatusApplyConfiguration) WithPowerState(value apiv1alpha1.ServerPowerState) *ServerStatusApplyConfiguration {
	b.PowerState = &value
	return b
}

// WithIndicatorLED sets the IndicatorLED field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IndicatorLED field is set to the value of the last call.
func (b *ServerStatusApplyConfiguration) WithIndicatorLED(value apiv1alpha1.IndicatorLED) *ServerStatusApplyConfiguration {
	b.IndicatorLED = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *ServerStatusApplyConfiguration) WithState(value apiv1alpha1.ServerState) *ServerStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithNetworkInterfaces adds the given value to the NetworkInterfaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NetworkInterfaces field.
func (b *ServerStatusApplyConfiguration) WithNetworkInterfaces(values ...*NetworkInterfaceApplyConfiguration) *ServerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNetworkInterfaces")
		}
		b.NetworkInterfaces = append(b.NetworkInterfaces, *values[i])
	}
	return b
}

// WithTotalSystemMemory sets the TotalSystemMemory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalSystemMemory field is set to the value of the last call.
func (b *ServerStatusApplyConfiguration) WithTotalSystemMemory(value resource.Quantity) *ServerStatusApplyConfiguration {
	b.TotalSystemMemory = &value
	return b
}

// WithProcessors adds the given value to the Processors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Processors field.
func (b *ServerStatusApplyConfiguration) WithProcessors(values ...*ProcessorApplyConfiguration) *ServerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProcessors")
		}
		b.Processors = append(b.Processors, *values[i])
	}
	return b
}

// WithStorages adds the given value to the Storages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Storages field.
func (b *ServerStatusApplyConfiguration) WithStorages(values ...*StorageApplyConfiguration) *ServerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithStorages")
		}
		b.Storages = append(b.Storages, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ServerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ServerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
