// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// ServerMaintenanceStatusApplyConfiguration represents a declarative configuration of the ServerMaintenanceStatus type for use
// with apply.
//
// ServerMaintenanceStatus defines the observed state of a ServerMaintenance
type ServerMaintenanceStatusApplyConfiguration struct {
	// State specifies the current state of the server maintenance.
	State *apiv1alpha1.ServerMaintenanceState `json:"state,omitempty"`
}

// ServerMaintenanceStatusApplyConfiguration constructs a declarative configuration of the ServerMaintenanceStatus type for use with
// apply.
func ServerMaintenanceStatus() *ServerMaintenanceStatusApplyConfiguration {
	return &ServerMaintenanceStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *ServerMaintenanceStatusApplyConfiguration) WithState(value apiv1alpha1.ServerMaintenanceState) *ServerMaintenanceStatusApplyConfiguration {
	b.State = &value
	return b
}
