// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// ServerClaimStatusApplyConfiguration represents a declarative configuration of the ServerClaimStatus type for use
// with apply.
//
// ServerClaimStatus defines the observed state of ServerClaim.
type ServerClaimStatusApplyConfiguration struct {
	// Phase represents the current phase of the server claim.
	Phase *apiv1alpha1.Phase `json:"phase,omitempty"`
}

// ServerClaimStatusApplyConfiguration constructs a declarative configuration of the ServerClaimStatus type for use with
// apply.
func ServerClaimStatus() *ServerClaimStatusApplyConfiguration {
	return &ServerClaimStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ServerClaimStatusApplyConfiguration) WithPhase(value apiv1alpha1.Phase) *ServerClaimStatusApplyConfiguration {
	b.Phase = &value
	return b
}
