// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// ServerMaintenanceSpecApplyConfiguration represents a declarative configuration of the ServerMaintenanceSpec type for use
// with apply.
//
// ServerMaintenanceSpec defines the desired state of a ServerMaintenance
type ServerMaintenanceSpecApplyConfiguration struct {
	// Policy specifies the maintenance policy to be enforced on the server.
	Policy *apiv1alpha1.ServerMaintenancePolicy `json:"policy,omitempty"`
	// ServerRef is a reference to the server that is to be maintained.
	ServerRef *v1.LocalObjectReference `json:"serverRef,omitempty"`
	// ServerPower specifies the power state of the server during maintenance.
	ServerPower *apiv1alpha1.Power `json:"serverPower,omitempty"`
	// Priority determines ordering when multiple ServerMaintenance resources target the same server.
	// Higher values are processed first. If priorities are equal, older resources are processed first.
	// If omitted, priority is treated as 0.
	Priority *int32 `json:"priority,omitempty"`
	// ServerBootConfigurationTemplate specifies the boot configuration to be applied to the server during maintenance.
	ServerBootConfigurationTemplate *ServerBootConfigurationTemplateApplyConfiguration `json:"serverBootConfigurationTemplate,omitempty"`
}

// ServerMaintenanceSpecApplyConfiguration constructs a declarative configuration of the ServerMaintenanceSpec type for use with
// apply.
func ServerMaintenanceSpec() *ServerMaintenanceSpecApplyConfiguration {
	return &ServerMaintenanceSpecApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *ServerMaintenanceSpecApplyConfiguration) WithPolicy(value apiv1alpha1.ServerMaintenancePolicy) *ServerMaintenanceSpecApplyConfiguration {
	b.Policy = &value
	return b
}

// WithServerRef sets the ServerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerRef field is set to the value of the last call.
func (b *ServerMaintenanceSpecApplyConfiguration) WithServerRef(value v1.LocalObjectReference) *ServerMaintenanceSpecApplyConfiguration {
	b.ServerRef = &value
	return b
}

// WithServerPower sets the ServerPower field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerPower field is set to the value of the last call.
func (b *ServerMaintenanceSpecApplyConfiguration) WithServerPower(value apiv1alpha1.Power) *ServerMaintenanceSpecApplyConfiguration {
	b.ServerPower = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *ServerMaintenanceSpecApplyConfiguration) WithPriority(value int32) *ServerMaintenanceSpecApplyConfiguration {
	b.Priority = &value
	return b
}

// WithServerBootConfigurationTemplate sets the ServerBootConfigurationTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerBootConfigurationTemplate field is set to the value of the last call.
func (b *ServerMaintenanceSpecApplyConfiguration) WithServerBootConfigurationTemplate(value *ServerBootConfigurationTemplateApplyConfiguration) *ServerMaintenanceSpecApplyConfiguration {
	b.ServerBootConfigurationTemplate = value
	return b
}
