// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	internal "github.com/ironcore-dev/metal-operator/api/v1alpha1/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ServerReadinessRuleApplyConfiguration represents a declarative configuration of the ServerReadinessRule type for use
// with apply.
//
// ServerReadinessRule is the Schema for the serverreadinessrules API
type ServerReadinessRuleApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration `json:",inline"`
	// metadata is a standard object metadata
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// spec defines the desired state of ServerReadinessRule
	Spec *ServerReadinessRuleSpecApplyConfiguration `json:"spec,omitempty"`
	// status defines the observed state of ServerReadinessRule
	Status *ServerReadinessRuleStatusApplyConfiguration `json:"status,omitempty"`
}

// ServerReadinessRule constructs a declarative configuration of the ServerReadinessRule type for use with
// apply.
func ServerReadinessRule(name string) *ServerReadinessRuleApplyConfiguration {
	b := &ServerReadinessRuleApplyConfiguration{}
	b.WithName(name)
	b.WithKind("ServerReadinessRule")
	b.WithAPIVersion("metal.ironcore.dev/v1alpha1")
	return b
}

// ExtractServerReadinessRuleFrom extracts the applied configuration owned by fieldManager from
// serverReadinessRule for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// serverReadinessRule must be a unmodified ServerReadinessRule API object that was retrieved from the Kubernetes API.
// ExtractServerReadinessRuleFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractServerReadinessRuleFrom(serverReadinessRule *apiv1alpha1.ServerReadinessRule, fieldManager string, subresource string) (*ServerReadinessRuleApplyConfiguration, error) {
	b := &ServerReadinessRuleApplyConfiguration{}
	err := managedfields.ExtractInto(serverReadinessRule, internal.Parser().Type("com.github.ironcore-dev.metal-operator.api.v1alpha1.ServerReadinessRule"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(serverReadinessRule.Name)

	b.WithKind("ServerReadinessRule")
	b.WithAPIVersion("metal.ironcore.dev/v1alpha1")
	return b, nil
}

// ExtractServerReadinessRule extracts the applied configuration owned by fieldManager from
// serverReadinessRule. If no managedFields are found in serverReadinessRule for fieldManager, a
// ServerReadinessRuleApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// serverReadinessRule must be a unmodified ServerReadinessRule API object that was retrieved from the Kubernetes API.
// ExtractServerReadinessRule provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractServerReadinessRule(serverReadinessRule *apiv1alpha1.ServerReadinessRule, fieldManager string) (*ServerReadinessRuleApplyConfiguration, error) {
	return ExtractServerReadinessRuleFrom(serverReadinessRule, fieldManager, "")
}

// ExtractServerReadinessRuleStatus extracts the applied configuration owned by fieldManager from
// serverReadinessRule for the status subresource.
func ExtractServerReadinessRuleStatus(serverReadinessRule *apiv1alpha1.ServerReadinessRule, fieldManager string) (*ServerReadinessRuleApplyConfiguration, error) {
	return ExtractServerReadinessRuleFrom(serverReadinessRule, fieldManager, "status")
}

func (b ServerReadinessRuleApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithKind(value string) *ServerReadinessRuleApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithAPIVersion(value string) *ServerReadinessRuleApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithName(value string) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithGenerateName(value string) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithNamespace(value string) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithUID(value types.UID) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithResourceVersion(value string) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithGeneration(value int64) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithCreationTimestamp(value metav1.Time) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ServerReadinessRuleApplyConfiguration) WithLabels(entries map[string]string) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ServerReadinessRuleApplyConfiguration) WithAnnotations(entries map[string]string) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *ServerReadinessRuleApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *ServerReadinessRuleApplyConfiguration) WithFinalizers(values ...string) *ServerReadinessRuleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *ServerReadinessRuleApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithSpec(value *ServerReadinessRuleSpecApplyConfiguration) *ServerReadinessRuleApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ServerReadinessRuleApplyConfiguration) WithStatus(value *ServerReadinessRuleStatusApplyConfiguration) *ServerReadinessRuleApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *ServerReadinessRuleApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *ServerReadinessRuleApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *ServerReadinessRuleApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *ServerReadinessRuleApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
