// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ServerReadinessRuleStatusApplyConfiguration represents a declarative configuration of the ServerReadinessRuleStatus type for use
// with apply.
//
// ServerReadinessRuleStatus defines the observed state of ServerReadinessRule.
type ServerReadinessRuleStatusApplyConfiguration struct {
	// conditions represent the current state of the ServerReadinessRule resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ServerReadinessRuleStatusApplyConfiguration constructs a declarative configuration of the ServerReadinessRuleStatus type for use with
// apply.
func ServerReadinessRuleStatus() *ServerReadinessRuleStatusApplyConfiguration {
	return &ServerReadinessRuleStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ServerReadinessRuleStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ServerReadinessRuleStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
