// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ServerMaintenanceRefItemApplyConfiguration represents a declarative configuration of the ServerMaintenanceRefItem type for use
// with apply.
//
// ServerMaintenanceRefItem is a reference to a ServerMaintenance object.
type ServerMaintenanceRefItemApplyConfiguration struct {
	// ServerMaintenanceRef is a reference to a ServerMaintenance object that the BMCSettings has requested for the referred server.
	ServerMaintenanceRef *ObjectReferenceApplyConfiguration `json:"serverMaintenanceRef,omitempty"`
}

// ServerMaintenanceRefItemApplyConfiguration constructs a declarative configuration of the ServerMaintenanceRefItem type for use with
// apply.
func ServerMaintenanceRefItem() *ServerMaintenanceRefItemApplyConfiguration {
	return &ServerMaintenanceRefItemApplyConfiguration{}
}

// WithServerMaintenanceRef sets the ServerMaintenanceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerMaintenanceRef field is set to the value of the last call.
func (b *ServerMaintenanceRefItemApplyConfiguration) WithServerMaintenanceRef(value *ObjectReferenceApplyConfiguration) *ServerMaintenanceRefItemApplyConfiguration {
	b.ServerMaintenanceRef = value
	return b
}
