// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ServerBootConfigurationTemplateApplyConfiguration represents a declarative configuration of the ServerBootConfigurationTemplate type for use
// with apply.
//
// ServerBootConfigurationTemplate defines the parameters to be used for rendering a boot configuration.
type ServerBootConfigurationTemplateApplyConfiguration struct {
	// Name specifies the name of the boot configuration.
	Name *string `json:"name,omitempty"`
	// Spec specifies the boot configuration to be rendered.
	Spec *ServerBootConfigurationSpecApplyConfiguration `json:"spec,omitempty"`
}

// ServerBootConfigurationTemplateApplyConfiguration constructs a declarative configuration of the ServerBootConfigurationTemplate type for use with
// apply.
func ServerBootConfigurationTemplate() *ServerBootConfigurationTemplateApplyConfiguration {
	return &ServerBootConfigurationTemplateApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServerBootConfigurationTemplateApplyConfiguration) WithName(value string) *ServerBootConfigurationTemplateApplyConfiguration {
	b.Name = &value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ServerBootConfigurationTemplateApplyConfiguration) WithSpec(value *ServerBootConfigurationSpecApplyConfiguration) *ServerBootConfigurationTemplateApplyConfiguration {
	b.Spec = value
	return b
}
