// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ServerClaimSpecApplyConfiguration represents a declarative configuration of the ServerClaimSpec type for use
// with apply.
//
// ServerClaimSpec defines the desired state of ServerClaim.
type ServerClaimSpecApplyConfiguration struct {
	// Power specifies the desired power state of the server.
	Power *apiv1alpha1.Power `json:"power,omitempty"`
	// ServerRef is a reference to a specific server to be claimed.
	ServerRef *v1.LocalObjectReference `json:"serverRef,omitempty"`
	// ServerSelector specifies a label selector to identify the server to be claimed.
	ServerSelector *metav1.LabelSelectorApplyConfiguration `json:"serverSelector,omitempty"`
	// IgnitionSecretRef is a reference to the Secret object that contains
	// the ignition configuration for the server.
	IgnitionSecretRef *v1.LocalObjectReference `json:"ignitionSecretRef,omitempty"`
	// UserDataRef references a Secret in the same namespace as this ServerClaim
	// containing user-data exposed to the claimed server via the metaldata
	// service. The referenced Secret must be of type metal.ironcore.dev/user-data.
	UserDataRef *v1.LocalObjectReference `json:"userDataRef,omitempty"`
	// Image specifies the boot image to be used for the server.
	Image *string `json:"image,omitempty"`
	// Tolerations allow a ServerClaim to bind to a Server with matching taints.
	Tolerations []TolerationApplyConfiguration `json:"tolerations,omitempty"`
}

// ServerClaimSpecApplyConfiguration constructs a declarative configuration of the ServerClaimSpec type for use with
// apply.
func ServerClaimSpec() *ServerClaimSpecApplyConfiguration {
	return &ServerClaimSpecApplyConfiguration{}
}

// WithPower sets the Power field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Power field is set to the value of the last call.
func (b *ServerClaimSpecApplyConfiguration) WithPower(value apiv1alpha1.Power) *ServerClaimSpecApplyConfiguration {
	b.Power = &value
	return b
}

// WithServerRef sets the ServerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerRef field is set to the value of the last call.
func (b *ServerClaimSpecApplyConfiguration) WithServerRef(value v1.LocalObjectReference) *ServerClaimSpecApplyConfiguration {
	b.ServerRef = &value
	return b
}

// WithServerSelector sets the ServerSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerSelector field is set to the value of the last call.
func (b *ServerClaimSpecApplyConfiguration) WithServerSelector(value *metav1.LabelSelectorApplyConfiguration) *ServerClaimSpecApplyConfiguration {
	b.ServerSelector = value
	return b
}

// WithIgnitionSecretRef sets the IgnitionSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnitionSecretRef field is set to the value of the last call.
func (b *ServerClaimSpecApplyConfiguration) WithIgnitionSecretRef(value v1.LocalObjectReference) *ServerClaimSpecApplyConfiguration {
	b.IgnitionSecretRef = &value
	return b
}

// WithUserDataRef sets the UserDataRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserDataRef field is set to the value of the last call.
func (b *ServerClaimSpecApplyConfiguration) WithUserDataRef(value v1.LocalObjectReference) *ServerClaimSpecApplyConfiguration {
	b.UserDataRef = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ServerClaimSpecApplyConfiguration) WithImage(value string) *ServerClaimSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *ServerClaimSpecApplyConfiguration) WithTolerations(values ...*TolerationApplyConfiguration) *ServerClaimSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTolerations")
		}
		b.Tolerations = append(b.Tolerations, *values[i])
	}
	return b
}
