// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// ServerSpecApplyConfiguration represents a declarative configuration of the ServerSpec type for use
// with apply.
//
// ServerSpec defines the desired state of a Server.
type ServerSpecApplyConfiguration struct {
	// SystemUUID is the unique identifier for the server.
	SystemUUID *string `json:"systemUUID,omitempty"`
	// SystemURI is the unique URI for the server resource in REDFISH API.
	SystemURI *string `json:"systemURI,omitempty"`
	// Power specifies the desired power state of the server.
	Power *apiv1alpha1.Power `json:"power,omitempty"`
	// IndicatorLED specifies the desired state of the server's indicator LED.
	IndicatorLED *apiv1alpha1.IndicatorLED `json:"indicatorLED,omitempty"`
	// ServerClaimRef is a reference to a ServerClaim object that claims this server.
	ServerClaimRef *ImmutableObjectReferenceApplyConfiguration `json:"serverClaimRef,omitempty"`
	// ServerMaintenanceRef is a reference to a ServerMaintenance object that maintains this server.
	ServerMaintenanceRef *ObjectReferenceApplyConfiguration `json:"serverMaintenanceRef,omitempty"`
	// BMCRef is a reference to the BMC object associated with this server.
	BMCRef *v1.LocalObjectReference `json:"bmcRef,omitempty"`
	// BMC contains the access details for the BMC.
	BMC *BMCAccessApplyConfiguration `json:"bmc,omitempty"`
	// BootConfigurationRef is a reference to a BootConfiguration object that specifies
	// the boot configuration for this server.
	BootConfigurationRef *ObjectReferenceApplyConfiguration `json:"bootConfigurationRef,omitempty"`
	// MaintenanceBootConfigurationRef is a reference to a BootConfiguration object that specifies
	// the boot configuration for this server during maintenance.
	MaintenanceBootConfigurationRef *ObjectReferenceApplyConfiguration `json:"maintenanceBootConfigurationRef,omitempty"`
	// BootOrder specifies the boot order of the server.
	BootOrder []BootOrderApplyConfiguration `json:"bootOrder,omitempty"`
	// BIOSSettingsRef is a reference to a biossettings object that specifies
	// the BIOS configuration for this server.
	BIOSSettingsRef *v1.LocalObjectReference `json:"biosSettingsRef,omitempty"`
	// Taints control which ServerClaims can be bound to this server.
	Taints []TaintApplyConfiguration `json:"taints,omitempty"`
	// ReclaimTaints specify which taints to add when a server transitions from
	// reserved to available state.
	ReclaimTaints []TaintApplyConfiguration `json:"reclaimTaints,omitempty"`
}

// ServerSpecApplyConfiguration constructs a declarative configuration of the ServerSpec type for use with
// apply.
func ServerSpec() *ServerSpecApplyConfiguration {
	return &ServerSpecApplyConfiguration{}
}

// WithSystemUUID sets the SystemUUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemUUID field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithSystemUUID(value string) *ServerSpecApplyConfiguration {
	b.SystemUUID = &value
	return b
}

// WithSystemURI sets the SystemURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemURI field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithSystemURI(value string) *ServerSpecApplyConfiguration {
	b.SystemURI = &value
	return b
}

// WithPower sets the Power field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Power field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithPower(value apiv1alpha1.Power) *ServerSpecApplyConfiguration {
	b.Power = &value
	return b
}

// WithIndicatorLED sets the IndicatorLED field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IndicatorLED field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithIndicatorLED(value apiv1alpha1.IndicatorLED) *ServerSpecApplyConfiguration {
	b.IndicatorLED = &value
	return b
}

// WithServerClaimRef sets the ServerClaimRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerClaimRef field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithServerClaimRef(value *ImmutableObjectReferenceApplyConfiguration) *ServerSpecApplyConfiguration {
	b.ServerClaimRef = value
	return b
}

// WithServerMaintenanceRef sets the ServerMaintenanceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerMaintenanceRef field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithServerMaintenanceRef(value *ObjectReferenceApplyConfiguration) *ServerSpecApplyConfiguration {
	b.ServerMaintenanceRef = value
	return b
}

// WithBMCRef sets the BMCRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMCRef field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithBMCRef(value v1.LocalObjectReference) *ServerSpecApplyConfiguration {
	b.BMCRef = &value
	return b
}

// WithBMC sets the BMC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BMC field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithBMC(value *BMCAccessApplyConfiguration) *ServerSpecApplyConfiguration {
	b.BMC = value
	return b
}

// WithBootConfigurationRef sets the BootConfigurationRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootConfigurationRef field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithBootConfigurationRef(value *ObjectReferenceApplyConfiguration) *ServerSpecApplyConfiguration {
	b.BootConfigurationRef = value
	return b
}

// WithMaintenanceBootConfigurationRef sets the MaintenanceBootConfigurationRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaintenanceBootConfigurationRef field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithMaintenanceBootConfigurationRef(value *ObjectReferenceApplyConfiguration) *ServerSpecApplyConfiguration {
	b.MaintenanceBootConfigurationRef = value
	return b
}

// WithBootOrder adds the given value to the BootOrder field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BootOrder field.
func (b *ServerSpecApplyConfiguration) WithBootOrder(values ...*BootOrderApplyConfiguration) *ServerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBootOrder")
		}
		b.BootOrder = append(b.BootOrder, *values[i])
	}
	return b
}

// WithBIOSSettingsRef sets the BIOSSettingsRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BIOSSettingsRef field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithBIOSSettingsRef(value v1.LocalObjectReference) *ServerSpecApplyConfiguration {
	b.BIOSSettingsRef = &value
	return b
}

// WithTaints adds the given value to the Taints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Taints field.
func (b *ServerSpecApplyConfiguration) WithTaints(values ...*TaintApplyConfiguration) *ServerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTaints")
		}
		b.Taints = append(b.Taints, *values[i])
	}
	return b
}

// WithReclaimTaints adds the given value to the ReclaimTaints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ReclaimTaints field.
func (b *ServerSpecApplyConfiguration) WithReclaimTaints(values ...*TaintApplyConfiguration) *ServerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReclaimTaints")
		}
		b.ReclaimTaints = append(b.ReclaimTaints, *values[i])
	}
	return b
}
