// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ServerBootConfigurationSpecApplyConfiguration represents a declarative configuration of the ServerBootConfigurationSpec type for use
// with apply.
//
// ServerBootConfigurationSpec defines the desired state of ServerBootConfiguration.
type ServerBootConfigurationSpecApplyConfiguration struct {
	// ServerRef is a reference to the server for which this boot configuration is intended.
	ServerRef *v1.LocalObjectReference `json:"serverRef,omitempty"`
	// Image specifies the boot image to be used for the server.
	Image *string `json:"image,omitempty"`
	// IgnitionSecretRef is a reference to the Secret object that contains
	// the ignition configuration for the server.
	IgnitionSecretRef *v1.LocalObjectReference `json:"ignitionSecretRef,omitempty"`
}

// ServerBootConfigurationSpecApplyConfiguration constructs a declarative configuration of the ServerBootConfigurationSpec type for use with
// apply.
func ServerBootConfigurationSpec() *ServerBootConfigurationSpecApplyConfiguration {
	return &ServerBootConfigurationSpecApplyConfiguration{}
}

// WithServerRef sets the ServerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerRef field is set to the value of the last call.
func (b *ServerBootConfigurationSpecApplyConfiguration) WithServerRef(value v1.LocalObjectReference) *ServerBootConfigurationSpecApplyConfiguration {
	b.ServerRef = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ServerBootConfigurationSpecApplyConfiguration) WithImage(value string) *ServerBootConfigurationSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithIgnitionSecretRef sets the IgnitionSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnitionSecretRef field is set to the value of the last call.
func (b *ServerBootConfigurationSpecApplyConfiguration) WithIgnitionSecretRef(value v1.LocalObjectReference) *ServerBootConfigurationSpecApplyConfiguration {
	b.IgnitionSecretRef = &value
	return b
}
