// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SettingsFlowItemApplyConfiguration represents a declarative configuration of the SettingsFlowItem type for use
// with apply.
type SettingsFlowItemApplyConfiguration struct {
	// Name is the name of the flow item.
	Name *string `json:"name,omitempty"`
	// Settings contains software (e.g. BIOS, BMC) settings as a map.
	Settings map[string]string `json:"settings,omitempty"`
	// Priority defines the order of applying the settings. Lower numbers have higher priority (i.e. lower numbers are applied first).
	Priority *int32 `json:"priority,omitempty"`
}

// SettingsFlowItemApplyConfiguration constructs a declarative configuration of the SettingsFlowItem type for use with
// apply.
func SettingsFlowItem() *SettingsFlowItemApplyConfiguration {
	return &SettingsFlowItemApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SettingsFlowItemApplyConfiguration) WithName(value string) *SettingsFlowItemApplyConfiguration {
	b.Name = &value
	return b
}

// WithSettings puts the entries into the Settings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Settings field,
// overwriting an existing map entries in Settings field with the same key.
func (b *SettingsFlowItemApplyConfiguration) WithSettings(entries map[string]string) *SettingsFlowItemApplyConfiguration {
	if b.Settings == nil && len(entries) > 0 {
		b.Settings = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Settings[k] = v
	}
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *SettingsFlowItemApplyConfiguration) WithPriority(value int32) *SettingsFlowItemApplyConfiguration {
	b.Priority = &value
	return b
}
