// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// StorageDriveApplyConfiguration represents a declarative configuration of the StorageDrive type for use
// with apply.
//
// StorageDrive defines the details of one storage drive.
type StorageDriveApplyConfiguration struct {
	// Name is the name of the storage drive.
	Name *string `json:"name,omitempty"`
	// MediaType specifies the media type of the storage device.
	MediaType *string `json:"mediaType,omitempty"`
	// Type specifies the type of the storage device.
	Type *string `json:"type,omitempty"`
	// Capacity specifies the size of the storage device in bytes.
	Capacity *resource.Quantity `json:"capacity,omitempty"`
	// Vendor specifies the vendor of the storage device.
	Vendor *string `json:"vendor,omitempty"`
	// Model specifies the model of the storage device.
	Model *string `json:"model,omitempty"`
	// State specifies the state of the storage device.
	State *apiv1alpha1.StorageState `json:"state,omitempty"`
}

// StorageDriveApplyConfiguration constructs a declarative configuration of the StorageDrive type for use with
// apply.
func StorageDrive() *StorageDriveApplyConfiguration {
	return &StorageDriveApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *StorageDriveApplyConfiguration) WithName(value string) *StorageDriveApplyConfiguration {
	b.Name = &value
	return b
}

// WithMediaType sets the MediaType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MediaType field is set to the value of the last call.
func (b *StorageDriveApplyConfiguration) WithMediaType(value string) *StorageDriveApplyConfiguration {
	b.MediaType = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *StorageDriveApplyConfiguration) WithType(value string) *StorageDriveApplyConfiguration {
	b.Type = &value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *StorageDriveApplyConfiguration) WithCapacity(value resource.Quantity) *StorageDriveApplyConfiguration {
	b.Capacity = &value
	return b
}

// WithVendor sets the Vendor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vendor field is set to the value of the last call.
func (b *StorageDriveApplyConfiguration) WithVendor(value string) *StorageDriveApplyConfiguration {
	b.Vendor = &value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *StorageDriveApplyConfiguration) WithModel(value string) *StorageDriveApplyConfiguration {
	b.Model = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *StorageDriveApplyConfiguration) WithState(value apiv1alpha1.StorageState) *StorageDriveApplyConfiguration {
	b.State = &value
	return b
}
