// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// StorageVolumeApplyConfiguration represents a declarative configuration of the StorageVolume type for use
// with apply.
//
// StorageVolume defines the details of one storage volume.
type StorageVolumeApplyConfiguration struct {
	// Name is the name of the storage volume.
	Name *string `json:"name,omitempty"`
	// Capacity specifies the size of the storage device in bytes.
	Capacity *resource.Quantity `json:"capacity,omitempty"`
	// Status specifies the status of the volume.
	State *apiv1alpha1.StorageState `json:"state,omitempty"`
	// RAIDType specifies the RAID type of the associated Volume.
	RAIDType *string `json:"raidType,omitempty"`
	// VolumeUsage specifies the volume usage type for the Volume.
	VolumeUsage *string `json:"volumeUsage,omitempty"`
}

// StorageVolumeApplyConfiguration constructs a declarative configuration of the StorageVolume type for use with
// apply.
func StorageVolume() *StorageVolumeApplyConfiguration {
	return &StorageVolumeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *StorageVolumeApplyConfiguration) WithName(value string) *StorageVolumeApplyConfiguration {
	b.Name = &value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *StorageVolumeApplyConfiguration) WithCapacity(value resource.Quantity) *StorageVolumeApplyConfiguration {
	b.Capacity = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *StorageVolumeApplyConfiguration) WithState(value apiv1alpha1.StorageState) *StorageVolumeApplyConfiguration {
	b.State = &value
	return b
}

// WithRAIDType sets the RAIDType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RAIDType field is set to the value of the last call.
func (b *StorageVolumeApplyConfiguration) WithRAIDType(value string) *StorageVolumeApplyConfiguration {
	b.RAIDType = &value
	return b
}

// WithVolumeUsage sets the VolumeUsage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeUsage field is set to the value of the last call.
func (b *StorageVolumeApplyConfiguration) WithVolumeUsage(value string) *StorageVolumeApplyConfiguration {
	b.VolumeUsage = &value
	return b
}
