// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// StorageApplyConfiguration represents a declarative configuration of the Storage type for use
// with apply.
//
// Storage defines the details of one storage device.
type StorageApplyConfiguration struct {
	// Name is the name of the storage device.
	Name *string `json:"name,omitempty"`
	// State specifies the state of the storage device.
	State *apiv1alpha1.StorageState `json:"state,omitempty"`
	// Volumes is a collection of volumes associated with this storage.
	Volumes []StorageVolumeApplyConfiguration `json:"volumes,omitempty"`
	// Drives is a collection of drives associated with this storage.
	Drives []StorageDriveApplyConfiguration `json:"drives,omitempty"`
}

// StorageApplyConfiguration constructs a declarative configuration of the Storage type for use with
// apply.
func Storage() *StorageApplyConfiguration {
	return &StorageApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithName(value string) *StorageApplyConfiguration {
	b.Name = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithState(value apiv1alpha1.StorageState) *StorageApplyConfiguration {
	b.State = &value
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *StorageApplyConfiguration) WithVolumes(values ...*StorageVolumeApplyConfiguration) *StorageApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumes")
		}
		b.Volumes = append(b.Volumes, *values[i])
	}
	return b
}

// WithDrives adds the given value to the Drives field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Drives field.
func (b *StorageApplyConfiguration) WithDrives(values ...*StorageDriveApplyConfiguration) *StorageApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDrives")
		}
		b.Drives = append(b.Drives, *values[i])
	}
	return b
}
