// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
)

// TaintApplyConfiguration represents a declarative configuration of the Taint type for use
// with apply.
//
// Taint represents a taint applied to a Server that restricts which
// ServerClaims can be bound to it.
type TaintApplyConfiguration struct {
	// Key is the taint key to be applied to a server.
	Key *string `json:"key,omitempty"`
	// Value is the taint value corresponding to the taint key.
	Value *string `json:"value,omitempty"`
	// Effect indicates the effect of the taint on ServerClaims that do not
	// tolerate the taint.
	Effect *apiv1alpha1.TaintEffect `json:"effect,omitempty"`
}

// TaintApplyConfiguration constructs a declarative configuration of the Taint type for use with
// apply.
func Taint() *TaintApplyConfiguration {
	return &TaintApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *TaintApplyConfiguration) WithKey(value string) *TaintApplyConfiguration {
	b.Key = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *TaintApplyConfiguration) WithValue(value string) *TaintApplyConfiguration {
	b.Value = &value
	return b
}

// WithEffect sets the Effect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Effect field is set to the value of the last call.
func (b *TaintApplyConfiguration) WithEffect(value apiv1alpha1.TaintEffect) *TaintApplyConfiguration {
	b.Effect = &value
	return b
}
