resources:
- ../default

patches:
#  --registry-url, --probe-os-image, --probe-image and --bmc-tools-image are mandatory flags.
# The following patch will add value for above flags
- path: manager_args_patch.yaml
  target:
    kind: Deployment
