apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  labels:
    topology.metal.ironcore.dev/rack: "2"
    topology.metal.ironcore.dev/heightunit: "10"
  name: server-2-10
spec:
  uuid: "12345"
  bmcRef:
    name: sample-bmc
  power: "Off"
  indicatorLED: "Off"
