variant: fcos
version: "1.3.0"
systemd:
  units:
    - name: var-lib-containerd.mount
      enabled: true
      contents: |-
        [Unit]
        Description=tmpfs for containerd image cache
        DefaultDependencies=no
        Before=containerd.service

        [Mount]
        What=tmpfs
        Where=/var/lib/containerd
        Type=tmpfs
        Options=mode=0700,size=4g

        [Install]
        WantedBy=multi-user.target
    - name: containerd.service
      enabled: true
      dropins:
        - name: 10-wait-mount.conf
          contents: |-
            [Unit]
            After=var-lib-containerd.mount
            Requires=var-lib-containerd.mount
    - name: metalprobe.service
      enabled: true
      contents: |-
        [Unit]
        Description=Run Metalprobe Container
        After=containerd.service
        Requires=containerd.service
        [Service]
        Restart=on-failure
        RestartSec=20
        ExecStartPre=/usr/bin/ctr images pull --skip-metadata {{.Image}}
        ExecStartPre=-/usr/bin/ctr tasks delete --force metalprobe
        ExecStartPre=-/usr/bin/ctr containers delete metalprobe
        ExecStart=/usr/bin/ctr run --rm --net-host --privileged {{.Image}} metalprobe ./launch.sh {{.Flags}}
        TimeoutSec=600
        [Install]
        WantedBy=multi-user.target
storage:
  files: []
passwd:
  users:
    - name: metal
      password_hash: {{.PasswordHash}}
      groups: [ "wheel" ]
      ssh_authorized_keys: [ {{.SSHPublicKey}} ]
