apiVersion: v1
kind: Service
metadata:
  name: metaldata
  namespace: system
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/component: metaldata
    app.kubernetes.io/managed-by: kustomize
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/component: metaldata
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
