apiVersion: v1
kind: ServiceAccount
metadata:
  name: metaldata
  namespace: system
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/component: metaldata
    app.kubernetes.io/managed-by: kustomize
