// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1/applyconfiguration/api/v1alpha1"
	internal "github.com/ironcore-dev/metal-operator/api/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=metal.ironcore.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("BMC"):
		return &apiv1alpha1.BMCApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCAccess"):
		return &apiv1alpha1.BMCAccessApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCSecret"):
		return &apiv1alpha1.BMCSecretApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCSpec"):
		return &apiv1alpha1.BMCSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCStatus"):
		return &apiv1alpha1.BMCStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCUser"):
		return &apiv1alpha1.BMCUserApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCUserSpec"):
		return &apiv1alpha1.BMCUserSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCUserStatus"):
		return &apiv1alpha1.BMCUserStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCVersion"):
		return &apiv1alpha1.BMCVersionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCVersionSpec"):
		return &apiv1alpha1.BMCVersionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCVersionStatus"):
		return &apiv1alpha1.BMCVersionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BMCVersionTemplate"):
		return &apiv1alpha1.BMCVersionTemplateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BootOrder"):
		return &apiv1alpha1.BootOrderApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConditionRequirement"):
		return &apiv1alpha1.ConditionRequirementApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConsoleProtocol"):
		return &apiv1alpha1.ConsoleProtocolApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Endpoint"):
		return &apiv1alpha1.EndpointApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("EndpointSpec"):
		return &apiv1alpha1.EndpointSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ImageSpec"):
		return &apiv1alpha1.ImageSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ImmutableObjectReference"):
		return &apiv1alpha1.ImmutableObjectReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InlineEndpoint"):
		return &apiv1alpha1.InlineEndpointApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("LLDPNeighbor"):
		return &apiv1alpha1.LLDPNeighborApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkInterface"):
		return &apiv1alpha1.NetworkInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectReference"):
		return &apiv1alpha1.ObjectReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Processor"):
		return &apiv1alpha1.ProcessorApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Protocol"):
		return &apiv1alpha1.ProtocolApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RetryPolicy"):
		return &apiv1alpha1.RetryPolicyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Server"):
		return &apiv1alpha1.ServerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerBootConfiguration"):
		return &apiv1alpha1.ServerBootConfigurationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerBootConfigurationSpec"):
		return &apiv1alpha1.ServerBootConfigurationSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerBootConfigurationStatus"):
		return &apiv1alpha1.ServerBootConfigurationStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerBootConfigurationTemplate"):
		return &apiv1alpha1.ServerBootConfigurationTemplateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerClaim"):
		return &apiv1alpha1.ServerClaimApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerClaimSpec"):
		return &apiv1alpha1.ServerClaimSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerClaimStatus"):
		return &apiv1alpha1.ServerClaimStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerMaintenance"):
		return &apiv1alpha1.ServerMaintenanceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerMaintenanceSpec"):
		return &apiv1alpha1.ServerMaintenanceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerMaintenanceStatus"):
		return &apiv1alpha1.ServerMaintenanceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerReadinessRule"):
		return &apiv1alpha1.ServerReadinessRuleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerReadinessRuleSpec"):
		return &apiv1alpha1.ServerReadinessRuleSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerReadinessRuleStatus"):
		return &apiv1alpha1.ServerReadinessRuleStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerSpec"):
		return &apiv1alpha1.ServerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerStatus"):
		return &apiv1alpha1.ServerStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Storage"):
		return &apiv1alpha1.StorageApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("StorageDrive"):
		return &apiv1alpha1.StorageDriveApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("StorageVolume"):
		return &apiv1alpha1.StorageVolumeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Taint"):
		return &apiv1alpha1.TaintApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Task"):
		return &apiv1alpha1.TaskApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Toleration"):
		return &apiv1alpha1.TolerationApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
