---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: fmi-server-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: metal-operator
    app.kubernetes.io/part-of: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: fmi-server-sa
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fmi-server-role
rules:
  - apiGroups:
      - metal.ironcore.dev
    resources:
      - bmcs
      - bmcsecrets
      - endpoints
      - serverbioses
      - servers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: fmi-server-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: metal-operator
    app.kubernetes.io/part-of: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: fmi-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fmi-server-role
subjects:
  - kind: ServiceAccount
    name: fmi-server-sa
    namespace: system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fmi-server
    app.kubernetes.io/instance: fmi-service
    app.kubernetes.io/component: fmi
    app.kubernetes.io/created-by: metal-operator
    app.kubernetes.io/part-of: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: fmi-server-svc
  namespace: system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9080
  selector:
    app.kubernetes.io/name: fmi-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fmi-server
    app.kubernetes.io/instance: fmi-server
    app.kubernetes.io/component: fmi
    app.kubernetes.io/created-by: metal-operator
    app.kubernetes.io/part-of: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: fmi-server
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fmi-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fmi-server
    spec:
      serviceAccountName: fmi-server-sa
      containers:
      - name: fmi-server
        command:
        - /fmi-server
        image: fmi-server:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9080
            protocol: TCP
      - name: redfish
        image: dmtf/redfish-mockup-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
