# This rule is not used by the project metal-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to metal.ironcore.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: biosversionset-viewer-role
rules:
- apiGroups:
  - metal.ironcore.dev
  resources:
  - biosversionsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - biosversionsets/status
  verbs:
  - get
