# permissions for end users to edit bmcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bmc-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: metal-operator
    app.kubernetes.io/part-of: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmc-editor-role
rules:
- apiGroups:
  - metal.ironcore.dev
  resources:
  - bmcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - bmcs/status
  verbs:
  - get
