apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSettingsSet
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmcsettingsset-sample
spec:
  bmcSettingsTemplate:
    version: "1.45.455b66-rev4"
    serverMaintenancePolicy: Enforced
    settings:
      BootMode: "UEFI"
      HyperThreading: "Enabled"
  bmcSelector:
    matchLabels:
      manufacturer: "dell"
      model: "poweredge-r840"
  dynamicSettings:
    - key: "AssetTag"
      valueFrom:
        bmcLabel: "metal.ironcore.dev/asset-tag"
    - key: "FQDN"
      format: "$(hostname).$(domain)"
      variables:
        hostname:
          bmcLabel: "metal.ironcore.dev/hostname"
        domain:
          configMapKeyRef:
            name: "network-config"
            namespace: "metal-system"
            key: "domain-suffix"
    - key: "LicenseKey"
      format: "$(region)-$(key)"
      variables:
        region:
          bmcLabel: "metal.ironcore.dev/region"
        key:
          secretKeyRef:
            name: "bmc-licenses"
            namespace: "metal-system"
            key: "{{ .bmcName }}"

