apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCVersion
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmcversion-sample
spec:
  version: "2.45.455b66-rev4"
  image:
    URI: "2.45.455b66-rev4"
    transferProtocol: "HTTPS"
  updatePolicy: Normal
  bmcRef:
    name: endpoint-sample
  serverMaintenancePolicy: OwnerApproval
