apiVersion: metal.ironcore.dev/v1alpha1
kind: BIOSSettings
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: biossettings-sample
spec:
  serverRef:
    name: endpoint-sample-system-0
  version: 2.10.2
  SettingsFlow:
    - name: abc
      priority: 10
      settings:
        PxeDev1EnDis: Enabled
  serverMaintenancePolicy: OwnerApproval
