apiVersion: metal.ironcore.dev/v1alpha1
kind: BMC
metadata:
  labels:
    app.kubernetes.io/name: bmc
    app.kubernetes.io/instance: bmc-sample
    app.kubernetes.io/part-of: metal-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: metal-operator
  name: bmc-sample
spec:
  endpointRef:
    name: endpoint-sample
  bmcSecretRef:
    name: bmc-sample
  protocol:
    name: Redfish
    port: 8080
