apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCVersion
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmcversion-sample
spec:
  version: "v2.34 (10/04/2024)"
  image:
    URI: "https://fooBMC-2.34_10_04_2024.signed.flash"
    transferProtocol: "HTTPS"
  updatePolicy: Normal
  BMCRef:
    name: sample-hpe-bmc
  serverMaintenancePolicy: OwnerApproval
