apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSettings
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/manufacturer: Lenovo
  name: bmcsettings-lenovo-sample
spec:
  BMCRef:
    name: endpoint-lenovo-sample
  version: TEI3E4A 4.11 2024-04-25
  priority: 10
  serverMaintenancePolicy: Enforced
  settingsFlow:
    - name: ntp
      priority: 0
      settings:
        "PATCH /redfish/v1/Managers/1/NetworkProtocol": '{"NTP": {"ProtocolEnabled": true, "NTPServers": ["timehost1", "timehost2", "timehost3"]}}'
    - name: snmp
      priority: 10
      settings:
        "PATCH /redfish/v1/Managers/1/NetworkProtocol": '{"SNMP": {"ProtocolEnabled": true, "Port": 161}}'
