apiVersion: metal.ironcore.dev/v1alpha1
kind: OOBMSettings
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: oobmsettings-sample
spec:
  serverRef:
    name: endpoint-sample-system-0
  OoBM:
    version: 7.00.00.171
    settings:
      ThermalSettings.1.FanSpeedOffset: "3"
  ServerMaintenancePolicyTemplate: Enforced