apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSettingsSet
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmcsettingsset-sample
spec:
  bmcSettingsTemplate:
    version: 2.10.3 # version to apply settings to
    serverMaintenancePolicy: OwnerApproval
    settings:
      foo: bar
      foo2: bar2
      dynamicfoo: "{{ inventory_hostname }}"
      dynamicfoo2: "{{ region }}"
      dynamicfoo3: "{{ licence_type }}"
  bmcSelector:
    matchLabels:
      manufacturer: "dell"
      model: "poweredge-r840"
  dynamicVariables:
      - name: inventory_hostname
        key: remote-bmc-dns-name
        objectKeyRef: 
            kind: ConfigMap
            name: my-configmap
            namespace: default
      - name: region
        bmcLabel: metal.ironcore.dev/region
      - name: licence_type
        objectKeyRef: 
            kind: Secret
            name: my-secret
            namespace: default
        key: licence_type

