apiVersion: metal.ironcore.dev/v1alpha1
kind: BMC
metadata:
  labels:
    manufacturer: "Contoso"
    app.kubernetes.io/name: bmc
    app.kubernetes.io/instance: bmc-sample
    app.kubernetes.io/part-of: metal-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: metal-operator
  name: bmc-sample
spec:
  access:
    ip: 127.0.0.1
  bmcSecretRef:
    name: bmcsecret-sample
  protocol:
    name: RedfishKube
    port: 8000

