apiVersion: metal.ironcore.dev/v1alpha1
kind: BIOSVersion
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: biosversion-sample
spec:
  version: "2.22.1"
  image:
    URI: "https://repo.eu-de-1.cloud.sap/hw-firmware/dell/poweredge-r640/BIOS_M73JJ_WN64_2.22.1.EXE"
    transferProtocol: "HTTPS"
  serverRef:
    name: node005-ap046-system-0 
  serverMaintenancePolicy: OwnerApproval
