apiVersion: metal.ironcore.dev/v1alpha1
kind: ServerBIOS
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: serverbios-sample
spec:
  serverRef:
    name: endpoint-sample-system-0
  bios:
    version: 2.10.3
    settings:
      PxeDev1EnDis: Disable
  ServerMaintenancePolicyTemplate: OwnerApproval
