apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSettings
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmcsettings-sample
spec:
  serverRef:
    name: endpoint-sample-system-0
  bmcSettingsSpec:
    version: 7.00.00.171
    settings:
      ThermalSettings.1.FanSpeedOffset: "3"
  serverMaintenancePolicyType: Enforced
