apiVersion: metal.ironcore.dev/v1alpha1
kind: BIOSVersionSet
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: biosversionset-sample
spec:
  biosVersionTemplate:
    version: "P80 v1.46 (12/06/2017)"
    image:
      URI: "P80 v1.46 (12/06/2017)"
      transferProtocol: "HTTPS"
    updatePolicy: Normal
    serverMaintenancePolicy: OwnerApproval
  serverSelector:
    matchLabels: 
      manufacturer: "Contoso"
