apiVersion: metal.ironcore.dev/v1alpha1
kind: BIOSVersion
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: biosversion-sample
spec:
  version: "P80 v1.45 (12/06/2017)"
  image:
    URI: "P80 v1.45 (12/06/2017)"
    transferProtocol: "HTTPS"
  updatePolicy: Normal
  serverRef:
    name: endpoint-sample-system-0
  serverMaintenancePolicy: OwnerApproval
