apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSettingsSet
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmcsettingsset-sample
spec:
  bmcSettingsTemplate:
    version: 2.10.3 # version to apply settings to
    serverMaintenancePolicy: OwnerApproval
    settings:
      foo: bar
      foo2: bar2
      dynamicfoo: "{{ inventory_hostname }}"
      dynamicfoo2: "{{ region }}"
      dynamicfoo3: "{{ licence_type }}"
  bmcSelector:
    matchLabels:
      manufacturer: "dell"
      model: "poweredge-r840"
  dynamicSettings:
    variables:
      - name: inventory_hostname
        objectIdentifier: my-configmap
        key: remote-bmc-dns-name
        type: configmap
        regexReplace:
          pattern: "-"
          replacement: "r-"
      - name: region
        key: metal.ironcore.dev/region
        type: label
      - name: licence_type
        objectIdentifier: my-secret
        key: licence_type
        type: secret
    ObjectKeyRefs:
      - identifier: my-configmap
        type: configmap
        objectRef:
          kind: ConfigMap
          name: my-configmap
          namespace: default
      - identifier: my-secret
        type: secret
        objectRef:
          kind: Secret
          name: my-secret
          namespace: default


