apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSettings
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmcsettings-sample
spec:
  BMCRef:
    name: endpoint-sample
  version: 1.45.455b66-rev4
  settings:
      abc: "3"
      # fqdn: `{{ RegexInsertOrReplace .labels.name "-" "r" }}` ->  endpoint-sample CRD will be used to get the value of "name" key from its labels (metadata) and replace using regex pattern "-" with "r"
      # license: `{{ GetSecretFrom "my-secret" "my-namespace" "key" }}` -> it will get the value of "key" from the secret "my-secret" in "my-namespace"
      # data: `{{ GetConfigData "my-config" "my-namespace" "key" }}` -> it will get the value of "key" from the configmap "my-config" in "my-namespace"
  serverMaintenancePolicy: Enforced
