apiVersion: metal.ironcore.dev/v1alpha1
kind: BIOSSettings
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: biossettings-sample
spec:
  serverRef:
    name: endpoint-sample-system-0
  version: P79 v1.45 (12/06/2017)
  settingsFlow:
    - name: abc
      priority: 10
      settings:
        abc: Enabled
  serverMaintenancePolicy: OwnerApproval
