apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSettings
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: bmcsettings-sample
spec:
  BMCRef:
    name: endpoint-sample
  version: 1.45.455b66-rev4
  serverMaintenancePolicy: Enforced
  settingsFlow:
    - name: baseline
      priority: 0
      settings:
        BootMode: "UEFI"
        HyperThreading: "Enabled"
        LicenseKey: "$(LicenseKey)"
        FQDN: "$(BmcName).$(SearchDomain)"
    - name: advanced-tuning
      priority: 10
      settings:
        PowerProfile: "MaxPerformance"
        TurboBoost: "Enabled"
  variables:
    - key: BmcName
      valueFrom:
        fieldRef:
          fieldPath: spec.BMCRef.name
    - key: SearchDomain
      valueFrom:
        configMapKeyRef:
          name: "bmc-network-config"
          namespace: "metal-system"
          key: "search-domain"
    - key: LicenseKey
      valueFrom:
        secretKeyRef:
          name: "bmc-licenses"
          namespace: "metal-system"
          key: "$(BmcName)"
