apiVersion: v1
data:
    password: U2tINW...
    pem: LS0tLS...    
    pub: c3NoLXJzY...
kind: Secret
metadata:
  name: ssh-key-for-server-boot-config-sample
  namespace: default
  ownerReferences:
  - apiVersion: metal.ironcore.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ServerBootConfiguration
    name: serverbootconfiguration-sample
    uid: "THIS NEEDS TO BE FILLED IN"
type: Opaque