// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	// LabelKeyPipeline is set on MaintenancePipelineRun objects to reference their owning pipeline.
	// Value: pipeline name.
	LabelKeyPipeline = "metal.ironcore.dev/pipeline"

	// LabelKeyPipelineBMC is set on MaintenancePipelineRun objects to identify the BMC they manage.
	// Value: BMC object name.
	LabelKeyPipelineBMC = "metal.ironcore.dev/bmc"

	// LabelKeyPipelineRun is set on child resources (BMCSettings, BMCVersion, BIOSSettings, BIOSVersion)
	// to reference the MaintenancePipelineRun that owns them.
	// Value: MaintenancePipelineRun name.
	LabelKeyPipelineRun = "metal.ironcore.dev/pipeline-run"

	// LabelKeyPipelineStage is set on child resources to identify the pipeline stage that created them.
	// Value: stage name (matches spec.stages[*].name in the parent MaintenancePipeline).
	LabelKeyPipelineStage = "metal.ironcore.dev/stage"

	// LabelKeyPipelineServer is set on Server-scoped child resources (BIOSSettings, BIOSVersion)
	// to identify the server they target within a pipeline stage.
	// Value: Server object name.
	LabelKeyPipelineServer = "metal.ironcore.dev/server"
)

// MaintenancePipelineRunPhase describes the current phase of a MaintenancePipelineRun or one of its stages.
type MaintenancePipelineRunPhase string

const (
	// MaintenancePipelineRunPhasePending indicates the run or stage has not yet started.
	MaintenancePipelineRunPhasePending MaintenancePipelineRunPhase = "Pending"
	// MaintenancePipelineRunPhaseInProgress indicates the run or stage is currently executing.
	MaintenancePipelineRunPhaseInProgress MaintenancePipelineRunPhase = "InProgress"
	// MaintenancePipelineRunPhaseCompleted indicates the run or stage has successfully completed.
	MaintenancePipelineRunPhaseCompleted MaintenancePipelineRunPhase = "Completed"
	// MaintenancePipelineRunPhaseFailed indicates the run or stage has failed.
	MaintenancePipelineRunPhaseFailed MaintenancePipelineRunPhase = "Failed"
)

// PipelineChildRef references a child resource (BMCSettings, BMCVersion, BIOSSettings, or BIOSVersion)
// created by a MaintenancePipelineRun.
type PipelineChildRef struct {
	// Kind is the kind of the child resource.
	// One of: BMCSettings, BMCVersion, BIOSSettings, BIOSVersion.
	// +required
	Kind string `json:"kind"`

	// Name is the generated name of the child resource.
	// +required
	Name string `json:"name"`
}

// MaintenancePipelineRunStageServerStatus tracks per-server progress for Server-scoped stages
// (BIOSSettings and BIOSVersion).
type MaintenancePipelineRunStageServerStatus struct {
	// ServerRef identifies the server this status entry describes.
	// +required
	ServerRef corev1.LocalObjectReference `json:"serverRef"`

	// Phase is the current phase for this server within the stage.
	// +required
	Phase MaintenancePipelineRunPhase `json:"phase"`

	// ChildRef references the child resource created for this server.
	// Nil until the stage reaches this server.
	// +optional
	ChildRef *PipelineChildRef `json:"childRef,omitempty"`
}

// MaintenancePipelineRunStageStatus is the observed status of a single stage within a Run.
type MaintenancePipelineRunStageStatus struct {
	// Name identifies the stage; matches spec.stages[*].name in the owning MaintenancePipeline.
	// +required
	Name string `json:"name"`

	// Phase is the aggregate phase for this stage.
	// For Server-scoped stages the aggregate reflects the slowest server; individual servers
	// advance to the next stage independently as soon as their own child completes.
	// +required
	Phase MaintenancePipelineRunPhase `json:"phase"`

	// ChildRef references the child resource for BMC-scoped stages (BMCSettings, BMCVersion).
	// Nil for Server-scoped stages — see Servers[*].ChildRef instead.
	// +optional
	ChildRef *PipelineChildRef `json:"childRef,omitempty"`

	// Servers tracks per-server status for BIOSSettings and BIOSVersion stages.
	// Empty for BMC-scoped stages.
	// +optional
	Servers []MaintenancePipelineRunStageServerStatus `json:"servers,omitempty"`

	// CompletedAt is the time at which this stage reached the Completed phase.
	// +optional
	CompletedAt *metav1.Time `json:"completedAt,omitempty"`
}

// MaintenancePipelineRunSpec defines the desired state of MaintenancePipelineRun.
// MaintenancePipelineRun objects are auto-generated by the MaintenancePipeline controller —
// one per unique BMC covered by the pipeline's serverSelector.
type MaintenancePipelineRunSpec struct {
	// BMCRef references the BMC that this Run manages.
	// Immutable after creation.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="bmcRef is immutable"
	// +required
	BMCRef corev1.LocalObjectReference `json:"bmcRef"`

	// ServerRefs is the list of servers sharing this BMC that are targeted by the pipeline.
	// All servers must have spec.bmcRef pointing to the same BMC as bmcRef.
	// +kubebuilder:validation:MinItems=1
	// +required
	ServerRefs []corev1.LocalObjectReference `json:"serverRefs"`
}

// MaintenancePipelineRunStatus defines the observed state of MaintenancePipelineRun.
type MaintenancePipelineRunStatus struct {
	// Phase is the current aggregate phase of this Run.
	// +optional
	Phase MaintenancePipelineRunPhase `json:"phase,omitempty"`

	// TotalStages is the total number of stages defined in the owning pipeline.
	// +optional
	TotalStages int32 `json:"totalStages,omitempty"`

	// PendingStages is the number of stages that have not yet started.
	// +optional
	PendingStages int32 `json:"pendingStages,omitempty"`

	// ActiveStages is the number of stages currently executing.
	// +optional
	ActiveStages int32 `json:"activeStages,omitempty"`

	// CompletedStages is the number of stages that have successfully completed.
	// +optional
	CompletedStages int32 `json:"completedStages,omitempty"`

	// FailedStages is the number of stages that have failed.
	// +optional
	FailedStages int32 `json:"failedStages,omitempty"`

	// Stages mirrors the owning pipeline's spec.stages list with per-stage progress tracking.
	// The controller populates this list when the Run is first reconciled.
	// +optional
	Stages []MaintenancePipelineRunStageStatus `json:"stages,omitempty"`

	// Conditions represents the latest observations of the Run.
	// +patchStrategy=merge
	// +patchMergeKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,1,rep,name=conditions"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=mpr
// +kubebuilder:printcolumn:name="BMC",type=string,JSONPath=`.spec.bmcRef.name`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Stages",type=integer,JSONPath=`.status.totalStages`
// +kubebuilder:printcolumn:name="Active",type=integer,JSONPath=`.status.activeStages`
// +kubebuilder:printcolumn:name="Completed",type=integer,JSONPath=`.status.completedStages`
// +kubebuilder:printcolumn:name="Failed",type=integer,JSONPath=`.status.failedStages`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// MaintenancePipelineRun is the Schema for the maintenancepipelineruns API.
// It is auto-generated by the MaintenancePipeline controller — one instance per unique BMC
// covered by the pipeline's serverSelector. It owns all BMCSettings, BMCVersion, BIOSSettings,
// and BIOSVersion child resources for both the BMC and all servers that share it.
type MaintenancePipelineRun struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MaintenancePipelineRunSpec   `json:"spec,omitempty"`
	Status MaintenancePipelineRunStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MaintenancePipelineRunList contains a list of MaintenancePipelineRun.
type MaintenancePipelineRunList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MaintenancePipelineRun `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MaintenancePipelineRun{}, &MaintenancePipelineRunList{})
}
