macPrefixes:
- macPrefix: f4
  manufacturer: dell
  protocol: Redfish
  port: 443
  type: bmc
  defaultCredentials:
    - username: automation
      password: Password12
  console:
    type: ssh
    port: 22
- macPrefix: 2c
  manufacturer: dell
  protocol: Redfish
  port: 443
  type: bmc
  defaultCredentials:
    - username: automation
      password: Password12
  console:
    type: SSH
    port: 22
- macPrefix: 7C
  manufacturer: hpe
  protocol: Redfish
  port: 443
  type: bmc
  defaultCredentials:
    - username: automation
      password: Password12
  console:
    type: ssh
    port: 22
