apiVersion: v1
kind: Service
metadata:
  name: metal-registry
  namespace: metal-operator-system
spec:
  ports:
    - name: registry-server
      port: 30000
      targetPort: 30000
  selector:
    control-plane: controller-manager
