name: Build and Publish Helm Chart

permissions:
  contents: read

on:
  push:
    branches:
    - main
    tags:
    - v*.*.*
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'docs/**'
    - '**/*.md'
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  publish-charts:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-chart')
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: v3.16.2
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Set charts version
      if: github.event_name == 'push'
      run: |
        sed -i "s/version: .*/version: ${GITHUB_REF_NAME#v}/" dist/chart/Chart.yaml
    - name: Run chart-releaser
      uses: bitdeps/helm-oci-charts-releaser@v0.1.4
      with:
        charts_dir: dist/chart
        skip_gh_release: true
        oci_registry: ghcr.io/${{ github.repository_owner }}/charts
        oci_username: ${{ github.actor }}
        oci_password: ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
